### ISSUE TITLE
Interested in a Java/Jersey/MongoDB version for the practicals section

### ISSUE THREAD

**Issue by stephenc** [addyosmani/backbone-fundamentals#104]
I'd be happy to help. fairly small example code similar to ruby/sinatra/mongodb

**Comment by addyosmani** [comment]
Hey @stephenc. At the moment, I don't think I'm going to have a chance to write a Java/Jersey implementation section as we're running into the last few weeks for the book to be worked on.

If you think you might have time to write a Java practical up with some notes, I can definitely include it as a bonus in the repo as I'm sure there are developers out there it would help.

**Comment by raDiesle** [comment]
Hi you,

In my opinion, the content of the book should be about practial backbone.js stuff,
not about some fancy ruby/mongo/node server side stuff. 
Backbone talks with urls, so I don't care, how the result is generated behind this url.

Having a look on the server-client mix pages, it's going to loose the focus of backbone.js
and there is no answer of the question, how to write more than a unstructured hello world example.

How do you think about it ?

**Comment by stephenc** [comment]
Well you still need a back end... I think including a Java/Jersey implementation would be good too... there are a number of gotchas that backbone has when your backend is very REST... not just a Java/Jersey issue I know, but gotchas none the less when you are coming from Java/Jersey's very REST background... also the java code is not that big.... mostly one or two classes, e.g.

  @Path("todos")
  public class ToDosResource {

```
@Context
private ServletContext servletContext;

@POST
@Consumes({MediaType.APPLICATION_JSON})
public Response doCreate(ToDo content, final @Context UriInfo ui) {
    content.setId(null);
    // next bit is normally in a helper method, not here but I am copy & pasting the functionality
    Mongo instance;
    try {
        instance = new Mongo("127.0.0.1");
    } catch (UnknownHostException e) {
        throw new IllegalStateException("Have to know the host 'localhost'", e);
    }
    DB db = instance.getDB("todo");
    DBCollection todos = db.getCollection("todos");
    WriteResult<ToDo,String> result = JacksonDBCollection.wrap(todos, Todo.class, String.class).insert(content);
    return Response.created(UriBuilder.fromPath("{id}").build(result.getSavedId())).build();
}

// etc
```

  }

The trick is to use the correct Java libs, and Jersey and Jackson with the mongo-jackson-wrapper library makes the whole thing near trivial

**Comment by raDiesle** [comment]
Hi Stephen !

I really like the idea to use a solid technique, most people are used to. I am a Java guy, too ( and using Jersey).
So to build bigger Enterprise Applications, a suited server side technologie should be chosen.

It's hard enough to think about client side.- That's what the book should explain!

Should we also talk about solid and well known server side technogies, or fancy trendy new server-side technologies ?

Is or should there any difference in backbone code, depending on the server side technologie you choose?
I don't think so. 
Should Java/Jersey be added to the book to the existing client-serverside examples:   sure, go for it !

**Comment by addyosmani** [comment]
Having reviewed the feedback on the book so far I've decided that it would make more sense to tackle stack-agnostic Backbone issues more as developers seem more interested in this type of content. We can/will however tackle your request at some point via TodoMVC.com, where our next set of apps will also demonstrate stack setting up.
