### ISSUE TITLE
Error (tag mismatch) in iBooks line 649 at column 295

### ISSUE THREAD

**Issue by coryalder** [addyosmani/backbone-fundamentals#107]
I just loaded this into iBooks and I get this notice on page 2:

Error on line 649 at column 295: Opening and ending tag mismatch: cpde line 0 and p

![iBooks error message](http://i.imgur.com/uyT9B.png)

**Comment by addyosmani** [comment]
Thanks for reporting this! I'll hopefully patch this soon.
