### ISSUE TITLE
Section: working with nested models

### ISSUE THREAD

**Issue by smashercosmo** [addyosmani/backbone-fundamentals#108]
It would be great to cover this in a book. Yes, I know that there are plenty of plugins that handle such situations, but anyway this is quite confusing topic. For example,  what will be the best approach to render multilevel menu from nested data, like categories and subcategories of goods.

**Comment by amite** [comment]
- 1 this.

**Comment by addyosmani** [comment]
Are you looking for something like http://antoviaque.org/docs/tutorials/backbone-relational-tutorial/ to be covered?

**Comment by addyosmani** [comment]
This was recently tackled.
