### ISSUE TITLE
Unnecessary test

### ISSUE THREAD

**Issue by kimjoar** [addyosmani/backbone-fundamentals#122]
It might be that I've misunderstood something from the text, but is the first text example under http://addyosmani.github.com/backbone-fundamentals/#collections-2 an example of a good test? I've copied it here for reference:

``` javascript
describe('Tests for TodoList', function() {

    it('Can add Model instances as objects and arrays.', function() {
        var todos = new TodoList();

        expect(todos.length).toBe(0);

        todos.add({ text: 'Clean the kitchen' });

        // how many todos have been added so far?
        expect(todos.length).toBe(1);

        todos.add([
            { text: 'Do the laundry', done: true }, 
            { text: 'Go to the gym'}
        ]);

        // how many are there in total now?
        expect(todos.length).toBe(3);
    });
...
```

This test only ensures that the Backbone framework works as expected, doesn't it?

**Comment by addyosmani** [comment]
The idea behind this test was to demonstrate testing that a collection is being correctly populated. This is indeed technically testing that Backbone works as expected but there are going to be situations where you're going to populate based on behaviour in your application and need to ensure the data you've added is actually there. For the time being I'll be keeping this test in there, but I'm happy to accept suggestions for improvements on it!
