### ISSUE TITLE
Small confusion of toJSON and JSON.stringify

### ISSUE THREAD

**Issue by dietervds** [addyosmani/backbone-fundamentals#124]
In The Basics -> Model -> Getters&Setters -> Model.get() it is said that Model.toJSON() returns the JSON string as shown in the code example.  
However, toJSON() rather returns an object. I think you might be referring to JSON.stringify()

As shown here: http://documentcloud.github.com/backbone/#Model-toJSON

(note: I'm just following along in the book since it's my first real Backbone.js confrontation, so I might be missing something :-) )

Cheers,

Dieter

**Comment by addyosmani** [comment]
Hey @dietervds. In the Model.get() section I mention 'If you would like to access or copy a model's attributes for purposes such as JSON stringification (e.g. for serialization prior to being passed to a view), this can be achieved using Model.toJSON()'. Specifically, using JSON.stringify() on top of this would be expected to give you the string representation whilst the toJSON() method would return an object as you mentioned.

Would this sound more clear?.

'If you would like to access or copy a model's attributes for purposes such as JSON stringification (e.g. for serialization prior to being passed to a view), this can be achieved using Model.toJSON(). Remember that this will return an object and JSON.stringify() should be used to get a string representation of the data'.

**Comment by dietervds** [comment]
Hi @addyosmani , yes I think that would help to make it more clear. Thanks!
I think my main confusion came from the code beneath it:

```
var myAttributes = myPhoto.toJSON();
console.log(myAttributes);
/* this returns { title: "My awesome photo", 
             src:"boston.jpg", 
             location: "Boston", 
             tags:['the big game', 'vacation']}*/
```

When executed, it returns 'object', not the json as a string as it would seem to say in the comment. Maybe this can be adapted to the following:

```
console.log(JSON.stringify(myattributes))
```

Note: when doing a PR on this book, which file do I change? :-) The index.md or is that generated?

**Comment by addyosmani** [comment]
I agree with that change. I assumed that it was clear this was the expanded object but on a second read you're absolutely right - it should be revised. 

If you'd like to make a PR, it would be great if you could do it against index.md. The rest of the formats are generated :)

**Comment by dietervds** [comment]
Good to know :-) PR is done: https://github.com/addyosmani/backbone-fundamentals/pull/125

**Comment by addyosmani** [comment]
Awesome. Closing now. PR merged!
