### ISSUE TITLE
Mention objects in `validate` function are passed by shallow copy.

### ISSUE THREAD

**Issue by fivetanley** [addyosmani/backbone-fundamentals#127]
I just wanted to start off by saying, **THANK YOU** for writing this book and making it available to the public.

I think (and this is just my personal opinion) that it is important to note that Backbone passed the `attributes` object by **shallow copy** to the `validate` function using `Underscore`'s `_.extend` function.  This means that you can't change any `Number` or `String` or `Boolean` attribute by reference in the way that you would expect a JavaScript object to behave normally.  However, because shallow copy does not copy objects by copying them, but by reference, you can change the attributes on those objects)

Example : http://jsfiddle.net/2NdDY/7/

Maybe I am the only one who thinks that attributes should be allowed to change when setting?

Is this more of an edge case? (e.g. filtering words or trimming strings)

**Comment by addyosmani** [comment]
Thanks! I've added a reference to the above for now. If we find during technical review after my planned re-write of the book that this is too much of an edge-case we might drop it but for now I think its worth keeping in.
