### ISSUE TITLE
Example of wrapping 3rd party libraries with require.js

### ISSUE THREAD

**Issue by erikcw** [addyosmani/backbone-fundamentals#13]
It would be great to see a section on wrapping 3rd party javascript libraries that are not AMD compatible.

**Comment by addyosmani** [comment]
Hey @erikcw! I'm moving this to the wishlist thread so it can be centrally coordinated there https://github.com/addyosmani/backbone-fundamentals/issues/3. 

Just to confirm: when you say wrapping 3rd party libraries, are you referring to things like say..google analytics or a retweet widget? Given that many of these now come with just a single external link to their JS source and some minor markup, I'm wondering if you're talking about wrapping this or the actual source in AMD.

Would most developers want to touch third party libraries in this way? (just thinking out loud) :)

**Comment by erikcw** [comment]
Hi @addyosmani 

I'm referring to a library like a jquery plugin, or https://github.com/PaulUithol/backbone-tastypie for example.

This library isn't currently setup to support AMD loaders, so to use it you have to create a require.js wrapper module and then access that wrapper from within the rest of your modules.  Does that make sense?  If there is a better pattern for this, I'm all ears.

**Comment by msteitle** [comment]
Very closely related to this (perhaps the same?) is keeping the global namespace clean when loading 3rd party libraries with requireJS. It would be great if there was a canonical way to load a library that doesn't have a noConflict method and still preserve the global namespace prior to loading your 3rd party JS in a page.
