### ISSUE TITLE
Typo in PhotosController

### ISSUE THREAD

**Issue by addyosmani** [addyosmani/backbone-fundamentals#138]
From the blog:

spelling mistake: 

=== editd

In this example, we're going to have a controller called `PhotosController which will be in charge of individual photos in the application. It will ensure that when the view updates (e.g a user editd the photo meta-data) the corresonding model does too.

**Comment by matt-richardson** [comment]
Addy - I think this has been fixed already, so can be closed.

**Comment by addyosmani** [comment]
You're correct. Thanks for the heads up!
