### ISSUE TITLE
reviews?

### ISSUE THREAD

**Issue by gmilby** [addyosmani/backbone-fundamentals#141]
re:http://shop.oreilly.com/product/0636920025344.do

Hey, are you reading the reviews?

Please do, i'm new to backbone too - it kept me from purchasing your book... include diagrams, flow, (topically) explain theories as you build, at a suitable point, if led to, offer more depth to the theory. 

OR better yet, just use some very cut and dry examples to show the features of the framework, then write another book explaining advanced usage?

j.m.h.o :)

**Comment by addyosmani** [comment]
Hi @gmilby. I am indeed reading the reviews. The Backbone.js book project is currently on hold until I wrap up my other book on JavaScript design patterns (which should be this week), but after that I'll be focusing on rewriting the basics section, expanding the areas that beginners can find most useful and adding more inline examples that don't require external access to view/use them. 

The rough cuts version of the book is very much just that - it was released to show readers we were working on a Backbone.js book project but I wouldn't say the current version is an indication of what the final one will look like at all. 

I'm happy to leave out some of the more advanced sections for another book or just as an extension to this one.

**Comment by gmilby** [comment]
Cool, posts the simple-inline examples & content if you want it tested.
Would like to 'get' this. Thanks Addy.
On Jun 6, 2012 8:15 AM, "Addy Osmani" <
reply@reply.github.com>
wrote:

**Comment by addyosmani** [comment]
Closing as review feedback is or has been addressed. Thanks!
