### ISSUE TITLE
Which content of backbone fundamentals?

### ISSUE THREAD

**Issue by raDiesle** [addyosmani/backbone-fundamentals#142]
Hi,
as I've already mentioned in another issue, I would prefer to have design patterns
in a seperate book ( as you do) as well as server side technologies.

I'm going to commit to this book,but for me it's not clear, what the content of the book should be.
I'd like to see more practical examples and fundamentals like described here:
http://aaronhardy.com/javascript/javascript-architecture-backbone-js-routers/

How do you think about it, Addy? 
Probably it's a good idea to think, discuss and vote about  a clear and nice structure of the content.

**Comment by addyosmani** [comment]
Hey @raDiesle. We've been reviewing the feedback coming through the O'Reilly site, Twitter, email and GitHub and its looking like readers want a book more focused on beginner content with a little less focus on design patterns and stacks and more focus on real-world examples of things you can build with Backbone. As such, once we've brainstormed what we think the contents should look like I'll create a new issue for discussion where the community can feed-back on whether they like the direction being taken or not.

Thanks!
