### ISSUE TITLE
minor typos and issues

### ISSUE THREAD

**Issue by swasical** [addyosmani/backbone-fundamentals#144]
for example Model.caption = 'A new caption' => for example, Model.caption = 'A new caption' 
If you want to create a new element for you view => your view
this collections titles => collection's
broken link: Rebecca Murphey's excellent article on the topic.
get '/member/_' do => should this be get '/members/_' do??
so we can load and instantiation => instantiate
You'll commonly see both this and the configuration object included the => included in the
Whilst we get with Backbone out of the box can be terribly useful => fix this sentence
Remember, If there => if there
Applications'. -> Applications.'

**Comment by addyosmani** [comment]
Thanks for the feedback! I'll make sure these get addressed soon.
