### ISSUE TITLE
I want to translate this book

### ISSUE THREAD

**Issue by 42thcoder** [addyosmani/backbone-fundamentals#148]
My I translate this book to Chinese and post on blog? Only my blog, is this OK?

**Comment by addyosmani** [comment]
Thanks for your interest in translation. Unfortunately the translation
rights are held by O'Reilly and beyond this repository and any translations
released via it we dont currently permit third party translations. There
are however plans to offer translations of the project in the future.

On Sunday, July 1, 2012, 42thcoder wrote:

> My I translate this book to Chinese and post on blog? Only my blog, is
> this OK?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/addyosmani/backbone-fundamentals/issues/148

## 

_Addy Osmani_

Developer Programs Engineer at Google
Blogger at: http://addyosmani.com
Phone: +44 7501 594 382
