### ISSUE TITLE
Incomplete references in backbone-fundamentals / index.html

### ISSUE THREAD

**Issue by Krzysztof-FF** [addyosmani/backbone-fundamentals#149]
Table Of Contents section in backbone-fundamentals / index.html has incomplete references starting from Backbone & jQuery Mobile and within Unit Testing, although appropriate paragraphs have been made completed.

**Comment by addyosmani** [comment]
When you say incomplete references you mean they haven't been linked up? There still appear to be some areas that aren't included in the TOC put we're going to work on fixing this soon.
