### ISSUE TITLE
Where do you bind a model and a view?

### ISSUE THREAD

**Issue by rwillmer** [addyosmani/backbone-fundamentals#155]
I'm reading the 'Views' section. 

It's clear how you create a view, but not how you bind it to a model.

In the example code for "Creating new views", there's a call in the render function which use this.model.toJSON() as a parameter.

It would be useful to have something in this example code to show how this gets set.

**Comment by rwillmer** [comment]
This is similar to #126.

+1 for the idea of more working code with explanations of why each line of code is there, starting from the smallest possible example of running Backbone code, building up to a working useful program.

**Comment by addyosmani** [comment]
So we're currently working on replacing all the basic section examples and will be addressing this there.
