### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by gnesher** [addyosmani/backbone-fundamentals#158]
Page 16 first paragraph "more as more" (duplicate more)

**Comment by addyosmani** [comment]
Thanks for the heads up!

**Comment by gnesher** [comment]
My pleasure - great book. 
Found a couple of additional typos should I open individual bugs or just send them all together ?

**Comment by addyosmani** [comment]
All together would be great thanks!
On 30 Jul 2012 20:13, "gnesher" <
reply@reply.github.com>
wrote:

**Comment by addyosmani** [comment]
Correction made to the latest markdown file. If you have any more bugs to report, feel free to let me know :)
