### ISSUE TITLE
Typo 'ca' should be 'can', also paragraph is confusing

### ISSUE THREAD

**Issue by homanchou** [addyosmani/backbone-fundamentals#166]
Note: Backbone passes the attributes object by shallow copy to the validate function using the Underscore _.extend method. This means that it is not possible to change any Number, String or Boolean attribute by reference in the way that one might expect a JavaScript object to behave. As shallow copy doesn't copy objects by implicitly copying them, but rather, by reference, one ca change the attributes on those objects.

An example of this (by @fivetanley) is available here.

I had to look at the example to figure out what you were saying.  Upon first read it seems like the first sentence contradicts the second sentence in that first you say it's not possible to change attributes, but then you say that it can change attributes.  The key difference is that one is talking about primatives and the other an object.  Sentence might be more intuitive the first time if stated this way: This means that it is not possible to change any Number, String or Boolean attribute but it IS possible to change attributes of objects because they are passed by reference.

**Comment by addyosmani** [comment]
I agree that the current version of the paragraph could definitely be improved. I'll land a commit with your suggested update to the sentence causing the most confusion with a view to further editing for readability at a later point. Thanks for reporting!.
