### ISSUE TITLE
Backbone modules

### ISSUE THREAD

**Issue by blackjk3** [addyosmani/backbone-fundamentals#18]
I have a question about the line between reusability vs. coupling within namespaced modules using backbone.  I have added a gist below describing a few different approaches.

https://gist.github.com/1514593

Thanks!

**Comment by addyosmani** [comment]
@blackjk3 before I reply, would you be more interested in an answer that covers the specific namespacing patterns you reference or one which targets how to handle this with RequireJS? (I only ask as my preference once apps start to get much bigger tends to be using an AMD-compatible loader like RequireJS which handles namespacing slightly differently)

**Comment by blackjk3** [comment]
@addyosmani using RequireJS is fine with me since it's more in line with your book.

**Comment by dlebedynskyi** [comment]
@addyosmani It would be quite nice if you provide more complex example with requireJs - how to build AMD with requireJS and backbone ? Thanks

**Comment by addyosmani** [comment]
@Demien87 could you define complex? Beyond the Todo + mobile apps what else would you like to see?

**Comment by dlebedynskyi** [comment]
@addyosmani  complex - it would be great to see  async model and controllers loading via requireJs - example maybe so - user adds component on page, require loads models views and controllers (backbone ets) - then some server data is requested for this specific component. This is how I see it :)  maybe even without jQuery Mobile
I see that you have practical example Practical: A Backbone, RequireJS/AMD app with jQuery Mobile - did not got to this yet.

**Comment by addyosmani** [comment]
@Demien87 So, if I'm not mistaken, you're after something that demonstrates loading components dynamically rather than on page load? (if it's simpler than that, feel free to say so). I think it would be useful to cover regardless.

**Comment by dlebedynskyi** [comment]
@addyosmani  yes you are correct - components dynamically rather than on page load. this would be great. Thanks

**Comment by OpenGrid** [comment]
Another perspective on AMD http://tomdale.net/2012/01/amd-is-not-the-answer/

**Comment by addyosmani** [comment]
We're going to address this in a new more complex app being worked on which will (hopefully) land with its own chapter.
