### ISSUE TITLE
Basic UI of the book

### ISSUE THREAD

**Issue by alexreynier** [addyosmani/backbone-fundamentals#194]
Firstly I would like to thank you ever so much for this fantastic guide! I have two requests actually...

The first: That the external links on your online book have the target="_blank" as it can be very frustrating being interested in reading some of the links you write but then losing the exact place in which you are at in the book - yes the placeholder markers help, but some of your chapters can be rather big especially if you are a little blind like me and need to have the font extra extra large!

The second: That the chapters on the online version be available in chapter chunks. Ie each main heading have its own page - its very easy to setup and would make it so much easier for someone reading the whole book online!

Other than that - great work!! Thank you very much!
Best Wishes.
XelionOne

**Comment by addyosmani** [comment]
I've been thinking about whether or not to split chapters out into separate pages. It would appear most other online books do this. I say let's do this after the next set of pending PRs land from external contributors. It'll be easier at that point.
