### ISSUE TITLE
Todo View file is called todos.js

### ISSUE THREAD

**Issue by stuartmemo** [addyosmani/backbone-fundamentals#196]
I found this filename slightly confusing because of its pluralisation. Made me think that this view handled all the todo items as one.  All other similar files in the project don't have the 's' on the end.

Thoughts?

**Comment by addyosmani** [comment]
Happy to adjust the filename to avoid confusion. Would you like to file a quick PR with the change (e.g todo.js or todoItem.js)? :)

**Comment by stuartmemo** [comment]
No probs! Done!

**Comment by addyosmani** [comment]
Fixed.
