### ISSUE TITLE
Does Backbone.Model inherits Backbone.Events or what is the term for it?

### ISSUE THREAD

**Issue by nonopolarity** [addyosmani/backbone-fundamentals#200]
It seems that some people may claim that Backbone.Model does not inherit Backbone.Events but simply mix it in, or how should it be better described?

http://stackoverflow.com/questions/13103684/for-backbone-js-how-to-show-that-backbone-model-inherits-from-backbone-events

**Comment by addyosmani** [comment]
Thanks for catching this. As the reply on SO states, the line in the book was incorrect. `Backbone.Events` is supposed to be used as a mixin. Earlier on, I actually do describe it as being used for mixing into other classes but for some reason I later say its used for inheritance. I've corrected this with the latest commits.
