### ISSUE TITLE
A bunch of little misprints

### ISSUE THREAD

**Issue by kipruss** [addyosmani/backbone-fundamentals#203]
1. a little misprint was found: 

``` javascript
var myAttributes = myPhoto.toJSON();
console.log(JSON.stringify(myattributes));
```

 uppercase of 'A'
1. Another perhaps little mistakes in the commented url strings like: 

``` javascript
/*Sample usage: http://unicorns.com/#  <about*/
```

 symbols ' <'.
1. It seems to me, an unnecessary extra 'to' is in the phrase "we don't need to to worry" (although I'm not sure)
2. In one of listings two spaces are passed, for example the listing, begins from:

``` javascript
// The Application
```

**Comment by addyosmani** [comment]
Thanks for the heads up! I'll fix these shortly, unless anyone else manages to apply these to index.md before I do.
