### ISSUE TITLE
epub without images

### ISSUE THREAD

**Issue by deepflame** [addyosmani/backbone-fundamentals#209]
Thanks a lot for this amazing work.
Just noticed on iBooks that the epub does not contain images (or at least they appear broken...)

**Comment by deepflame** [comment]
ok, just saw that the images were missing in all compiled versions.
Great that there is actually a pull request to fix that already...

https://github.com/addyosmani/backbone-fundamentals/pull/208

**Comment by addyosmani** [comment]
Really appreciate the heads up about this :) Fix merged!
