### ISSUE TITLE
Content scope

### ISSUE THREAD

**Issue by addyosmani** [addyosmani/backbone-fundamentals#216]
As we've been working on this project for a year, I think it's a good time to review what content we have and see what we can do to wrap up a 'final' first version before the end of 2012 :)

I've been looking through the index and feel like in order for us to give beginners the focused information they need, whilst also limiting scope enough that we can finish the book, the following changes should be made:
- Drop the section(s) on RESTful application development, instead replacing them with a shorter chapter on RESTful APIs and Backbone. This doesn't have to talk about a specific stack but could still use tutorial information. I think at the moment it looks like we're going to start talking about how to setup each possible stack and that gets away from Backbone too much in my opinion.
- Drop the section on mobile. We do have some good tips on Backbone + mobile, but I feel like we can condense that down to a page we can merge into general tips. Other than that I don't see there being too many mobile-specific problems that we're solving and it would again, help us clean up on scope.
- Modular/RequireJS: I feel like we can clean up that section to use the latest version of the TodoMVC RequireJS app https://github.com/addyosmani/todomvc/tree/gh-pages/dependency-examples/backbone_require and a little more of http://addyosmani.com/writing-modular-js/.
- Rethink whether we include the section on large-scale development
- Better conclusions section

What do you think @g6scheme @sindresorhus?

**Comment by sindresorhus** [comment]
I haven't gotten around to finish the book yet :/, so I can only comment on the above.

I agree with not divulging too much into all the stack, that's a word count slippery slope. The most important part to mention on the mobile part is correct memory management and network requests, other than that, there isn't too much specifics regarding Backbone on mobile. Using the latest TodoMvC app would certainly be preferable. Conclusion: Backbone is great in many scenarios, but know its strong and weakpoints.

**Comment by gschema** [comment]
Hi @addyosmani, 
@sindresorhus,
- I absolutely agree with you Addy on first two points.
- Also, regarding the idea about "the section on large-scale development", do you think writing additional chapter on that or extending further [Modular Development chapter](http://addyosmani.github.com/backbone-fundamentals/#modular-development)?
  I think splitting up that chapter would make sense. New chapter ~"the section on large-scale development" should follow chapter on Modular Development, as well as pull in content from it on [Decoupling Backbone with the Mediator and Facade Patterns](http://addyosmani.github.com/backbone-fundamentals/#decoupling-backbone-with-the-mediator-and-facade-patterns) and [Backbone.Marionette](http://addyosmani.github.com/backbone-fundamentals/#backbone.marionette) and then further extend on that. I think it would add value to readers to have separate chapter like that (though, generally, the subject is addressed throughout the whole book).

Btw, I started a bit of work on enhancement of [MVC intro section we discussed](https://github.com/addyosmani/backbone-fundamentals/pull/189#issuecomment-9969596). Do you wanna me to continue on that? Also, if work on that and time permits I could do Modular/RequireJS clean up you mentioned, so you could concentrate on "the section on large-scale development".

**Comment by addyosmani** [comment]
@sindresorhus I agree on mobile :) We'll probably end up still having a chapter on it, but focusing on best practice advice moreso than just the Todo app rendered on mobile. People would probably get more out of the former I think. ++ on the conclusions. I'll work on expanding the conclusion chapter.

@g6scheme

Thanks for the input!
- I think that a dedicated chapter to large-scale development would make sense (if we still want to cover it in the book). I also agree about it following the section on modular development for sure. You're right that we could pull in content from the two sections you cited for it. 
- Thanks so much for beginning work on the enhancement of the MVC section. If you could continue on that it would be fantastic. If you do also get a chance to look at cleaning up the Modular/RequireJS section that would be great. I think the important things to cover there beyond the basics are the shim config introduced in RequireJS 2.0 and general workflow. 
- On the large-scale section, do you think we should approach that as a general topic section or in the context of the Aura framework https://github.com/addyosmani/aura? I ask because if its the latter it would probably fit best in a general 'extensions' section, whilst the former might be more focused on patterns. I can work further on this for sure. 

Does everyone agree about us moving content we're (for now) dropping to the wiki?

**Comment by gschema** [comment]
@addyosmani 
Regarding 3rd point I think that it would be good large scale section to be approached as general topic section. That way readers would get insight/lesson on JS object oriented design basically, which would lead to easier understanding of the solutions like Aura, Marionette and decisions behind them.

About "moving content we're (for now) dropping to the wiki" works for me.
