### ISSUE TITLE
Basic JavaScript MVC implementation section

### ISSUE THREAD

**Issue by gschema** [addyosmani/backbone-fundamentals#222]
Hey @addyosmani 
I passed you an email about this section in .doc (bad idea :), so I thought it would be more convenient to transfer it to github.

Anyway, I did majority of the work on this:
https://gist.github.com/4157554

What's left is to improve comments a bit and improve/change the usage section and its comments.

I was wandering if you have some suggestions on the subject covered so far (and in general)?

Tnx,
Dusan

**Comment by addyosmani** [comment]
Thanks so much, Dusan! I've been travelling this week but did take a look at the doc earlier and thought you did a great job. We might want to tighten the grammar a little, but I'm happy to provide some inline comments on a few things we might want to improve. Again, really appreciate you looking at this.

We'll definitely want to expand on our comments in the cranium framework example. I know it currently also has a few bugs I need to fix :) Is there anything else in the current MVC introduction that we want to salvage or is this to replace it? 

I like the overall direction at the moment. We might want to drop (or simplify/expand on) the section talking about regions of the page and each of them being an MVC block. They certainly can be bug for beginners we want to talk about the most basic use-cases then lead them onto that. I think we currently do that a bit, but I'll think about how else it can be improved.

Hopefully will comment back soon (and thanks for the gist too!)

**Comment by gschema** [comment]
> We might want to tighten the grammar a little

Oh, yeah grammar, it's the [ESL](http://en.wikipedia.org/wiki/English_as_a_foreign_or_second_language) thing. It begs for editing, I guess. :)

> Is there anything else in the current MVC introduction that we want to salvage or is this to replace it?

That was probably my biggest question. I thought to merge it with [MVC](http://addyosmani.github.com/backbone-fundamentals/#mvc) and [MVC As We Know It](http://addyosmani.github.com/backbone-fundamentals/#mvc-as-we-know-it) sections. There is many valuable information in it. If you agree I would get into the merge process asap. That would need editing that's for sure, but we could do that through PRs.

> We might want to drop (or simplify/expand on) the section talking about regions of the page and each of them being an MVC block.

I added this explanation as it was somewhat revealing to me once I started looking at the pages as set of MVC stacks with each taking care of one logical part of it. I think it could benefit to the readers to see bigger picture from the start, but I probably haven't put it out that well, so it should be improved (better explained), expanded. What do you think, suggest?

Thanks.

**Comment by addyosmani** [comment]
I would love to see what a merge of MVC and MVC as we know it might look like. One complaint we got was that we focus a little too much at the start on explaining MVC before we get into Backbone and anything that shortens/adds more value to that chapter would be very welcome.

> What do you think, suggest? 

I'll think about this a little more and get back to you sir :)

**Comment by gschema** [comment]
@addyosmani Uh ah, I think I actually extended it a bit, though I still have to work on it. I think I see where the source of the complaint comes from and will try to fix it during this merge process.

I will send you pull request later today, so you can check current state.

This supposed to be finished already, but some unplanned things changed schedule a bit. I think I will manage to push it faster.

**Comment by addyosmani** [comment]
I really appreciate that :) Thank you!

**Comment by addyosmani** [comment]
Hey @g6scheme :) How are things going? I left a few comments on the PR about MVC. Will ping on a few other threads. Really appreciate your help once again!

**Comment by addyosmani** [comment]
Should we close this in favor of #230?

**Comment by gschema** [comment]
Hi @addyosmani 
I agree. 
I've been busy these days. didn't replied right away, but didn't comprehended it was 13 days ago. Uh.
