### ISSUE TITLE
Todos app does not work at #in-action chapter

### ISSUE THREAD

**Issue by pinksy** [addyosmani/backbone-fundamentals#225]
Implementing the todos app as far as http://addyosmani.github.com/backbone-fundamentals/#in-action does not work:

Uncaught TypeError: Cannot call method 'replace' of undefined underscore-min.js:5
Uncaught TypeError: undefined is not a function 

...because at that point in the tutorial, the #item-template and #stats-template templates have not been defined. Script tags (can be empty) to define the templates are needed in the <body> tag of index.html, anywhere before the view scripts are defined. E.g.,

...
<script src="js/collections/todos.js"></script>
**<script type="text/template" id="item-template"></script>**
**<script type="text/template" id="stats-template"></script>**
<script src="js/views/todo.js"></script>
...

**Comment by addyosmani** [comment]
I agree that we should address this. Originally I had wanted to just cover the most important parts of the codebase in the tutorial but it looks like a few pieces slipped in the process. We'll make sure to cover before the next release.
