### ISSUE TITLE
Please add an example to fetch when a custom HTTP header is required

### ISSUE THREAD

**Issue by mariusa** [addyosmani/backbone-fundamentals#23]
Hi,

Some APIs require a custom Authorization header to be set with a valid token in order to work.
Would you please add an example to "Fetching models from the server" section which shows how to set custom HTTP headers? 

Thanks

**Comment by mariusa** [comment]
Found the solution:
fetch( {headers: {'Authorization' : token} } );

Hope it will work in a similar way for POST/PUT/DELETE

**Comment by addyosmani** [comment]
Thanks @mariusa. This is going to get referenced in the wishlist.
