### ISSUE TITLE
Improving the AMD/RequireJS section

### ISSUE THREAD

**Issue by addyosmani** [addyosmani/backbone-fundamentals#233]
Some recent inspiration:
- http://kilon.org/blog/2012/08/build-backbone-apps-using-requirejs/ (Todo app)
- http://aaronhardy.com/javascript/javascript-architecture-requirejs-dependency-management/ (more detailed but also quite good)
- http://backbonetutorials.com/organizing-backbone-using-modules/
- http://jcreamerlive.com/2011/12/09/backbonejs-modular-app-using-requirejs/
- http://gregfranko.com/blog/using-backbone-dot-js-with-require-dot-js/
- http://jeremyckahn.github.com/blog/2012/08/18/keeping-it-sane-backbone-views-and-require-dot-js/
- http://kilon.org/blog/2012/08/testing-backbone-requirejs-applications-with-jasmine/
- http://net.tutsplus.com/tutorials/javascript-ajax/building-a-scalable-app-with-backbone-js/
- http://davidgranado.com/demos/todo-example/

**Comment by addyosmani** [comment]
From an email I wrote to Jack Franklin earlier. I think the ideal structure for this would be:
- Maintainability problems of multiple script files/HTTP overhead
- Need for better dep. management in JS
- AMD
- RequireJS
- Examples (e.g define/require/shim)
- Require + Backbone/Backbone Boilerplate

**Comment by jackfranklin** [comment]
@addyosmani the above structure sounds good to me. I'd also perhaps like to add a section in on the R.js optimiser? Wouldn't be too long at all, but I think it's worth a mention.

**Comment by addyosmani** [comment]
@jackfranklin Definitely! We have a section on managing packages with Require.js and r.js but an intro to r.js would be perfect.

**Comment by jackfranklin** [comment]
Great! I'll do some initial planning and reading of the above material when I can soon :)

**Comment by addyosmani** [comment]
@jackfranklin how are things going? :) If you need any help with direction or a review, please feel free to let me know. Thanks once again for graciously agreeing to help out with this.

**Comment by jackfranklin** [comment]
@addyosmani sorry for the radio silence - hoping to have something to show you by tomorrow! It wont be done by any means but should show you what I'm aiming for.

**Comment by addyosmani** [comment]
Let's continue this in #275
