### ISSUE TITLE
Problem building from source on Windows

### ISSUE THREAD

**Issue by chester89** [addyosmani/backbone-fundamentals#234]
Hi guys, 
I can't build anything on Windows using make - it says that file isn't found. I'm guessing problem is that I don't have the library you use to generate PDF files. How can I get it?

**Comment by chester89** [comment]
Forgive my dumbness, I think I figured it out. Thanks for your hard work

**Comment by chester89** [comment]
I turned out that my method didn't work - I downloaded texLive, but it installed a horrible amount of something on my machine and crashed during installation process. any other way to get make working?

**Comment by addyosmani** [comment]
Hmm. There's also http://www.miktex.org/ and http://w32tex.org/. If all else fails, you could use pandoc to export to HTML/your alternative format of choice then print to PDF.

**Comment by chester89** [comment]
Trying miktex now, will see how it goes

**Comment by chester89** [comment]
no way, same error again :(

**Comment by chester89** [comment]
I think I'll start reading rtf version and then give PDF conversion one more shot

**Comment by addyosmani** [comment]
I've patched issues that we were experiencing building for Mac in master. Could you try the windows build again to see if thats improved?

**Comment by addyosmani** [comment]
Closing in favor of #284
