### ISSUE TITLE
Acronyms used without definitions

### ISSUE THREAD

**Issue by lastcoolnameleft** [addyosmani/backbone-fundamentals#235]
While sequentially reading the book the term MVC is defined; however, the following aren't:
- MVP (Page 20 of PDF) - This is defined later in the book, but this is the first time the reader has encountered this acronym
- MVVM (Page 20 of PDF) -  Same as above
- GoF (Page 22 of PDF) - The acronym is defined; however, there's no context to the authors of "Design Patterns", which can be confusing for a reader not familiar with them.

There might be more, but these are the ones I've encountered thus far.

Cheers,
-Tommy.

**Comment by addyosmani** [comment]
Thanks for reporting this once again!
