### ISSUE TITLE
.getByCid code in The Internals: Collections no longer works with BackBone 0.9.9

### ISSUE THREAD

**Issue by beegle** [addyosmani/backbone-fundamentals#236]
The second code example in "The Internals :: Collections :: Getters and Setters" no longer works with BackBone 0.9.9. The current code is:

``` javascript
var todoCid = todos.getByCid(todo2.cid);
```

The [Change Log](http://backbonejs.org/#changelog) for 0.9.9 notes:

> Removed getByCid from Collections. collection.get now supports lookup by both id and cid.

The code I used to get the example working was simply to change collection.getByCid to collection.get.

``` javascript
var todoCid = todos.get(todo2.cid);
```

**Comment by addyosmani** [comment]
Thank you for the heads up! I'll get this fixed right away. If you notice anything else that's changed
in 0.9.9 as you read along I'd be happy to update that as well. Cheers!
