### ISSUE TITLE
Typo: un-opionated -> un-opinionated

### ISSUE THREAD

**Issue by erichiggins** [addyosmani/backbone-fundamentals#241]
First sentence of the Thorax section.
http://addyosmani.github.com/backbone-fundamentals/#thorax

**Comment by ugisozols** [comment]
@erichiggins hope you don't mind me opening PR with your fix :)

**Comment by erichiggins** [comment]
@ugisozols Thanks for taking care of it!

**Comment by addyosmani** [comment]
Thanks again!
