### ISSUE TITLE
Split book into multiple files?

### ISSUE THREAD

**Issue by jackfranklin** [addyosmani/backbone-fundamentals#248]
Addy, not sure how you'll feel about this but I was wondering if you'd considered splitting up the contents into multiple markdown files, perhaps 1 per chapter? The current `index.md` file is a monster which makes it a bit difficult to traverse and search, compared to having 1 file per chapter.

It would be fairly trivial to add something to the `Makefile` that merges them into one before the book is generated - I'd be happy to contribute that too.

Just a thought that popped into my head and I thought I'd see what the consensus is.

**Comment by addyosmani** [comment]
I fully agree with this, Jack and it's something that's been discussed once before. I would be happy for us to break down the book into individual chapter files and if you would be up for contributing the split/Makefile that would be even more awesome. Thanks for bringing the idea up!

**Comment by ugisozols** [comment]
:+1: for splitting as that was the first thought that popped in my head when I saw single index.md file.

**Comment by jackfranklin** [comment]
Great, I'll take a look at doing this :)
