### ISSUE TITLE
Re-write the Backbone.js + jQuery mobile chapter

### ISSUE THREAD

**Issue by addyosmani** [addyosmani/backbone-fundamentals#256]

**Comment by raDiesle** [comment]
I'll take the responsibility and rewrite the chapter, by adding a tutorial about how to create a  TODO-MVC jQuery Mobile app with Backbone. Anyone else wants to join?

**Comment by addyosmani** [comment]
@raDiesle Thanks once again. I'll try to get someone else to help you, but please feel free to make a start if you think you'll have time. We'd love to have this in :)

**Comment by addyosmani** [comment]
@raDiesle have you had a chance to get a start on this? :)

**Comment by raDiesle** [comment]
Yeah buzy, but on it. Next weekend I will commit.

**Comment by addyosmani** [comment]
Great! That's awesome. Thank you.

**Comment by raDiesle** [comment]
Hi, to let you now, about the current status:

I created a document to let people review at the end of next week:
https://docs.google.com/document/d/19Rk6mMxuUQfLjhKll5ACOapJyoQJ2bMha8lkg_J80n4/edit

I expect to have the time next week to create a complete draft version and commit the chapter to backbone-fundamentals as well as the jQM TODO app to the TODO-MVC page.

**Comment by addyosmani** [comment]
@raDiesle Thanks for sharing your initial draft. It's going in the right direction and I look forward to seeing your complete draft. I really appreciate you spending time on this. 

I'm happy to add some comments to the doc once you're closer to completing.

**Comment by addyosmani** [comment]
@raDiesle just pinging to check if you've had time to work on this further :)

**Comment by raDiesle** [comment]
Ya,

I would say, I can finish the article at the end of the week.
Further on, I'd like to add some improvements like precaching pages
or handling advanced situations.
How about the status of the rest?
