### ISSUE TITLE
The link to the Marionette Todo App repo is broken

### ISSUE THREAD

**Issue by jdreesen** [addyosmani/backbone-fundamentals#260]
Its somewhere around line 5903 and points to: https://github.com/derickbailey/todomvc/tree/master/labs/architecture-examples/backbone_marionette_modules/js

I wasn't able to figure out the correct link, so I created this issue instead of a pull request.

**Comment by jdreesen** [comment]
This link is also used around line 6388.

**Comment by wibblymat** [comment]
I found it on a branch within that repo - https://github.com/derickbailey/todomvc/tree/marionette/labs/architecture-examples/backbone_marionette/js

**Comment by addyosmani** [comment]
Thanks @wibblymat! Would you be up for filing a PR to correct the link?
