### ISSUE TITLE
Inconsistency in Marionette section

### ISSUE THREAD

**Issue by erichiggins** [addyosmani/backbone-fundamentals#263]
In the ToDo Application example, there are inconsistencies within the module definitions.
Specifically, you are extending from `Backbone.Marionette` in some modules, and from `Marionette` in others.  Both `Backbone` and `Marionette` are provided to the module as function parameters, so both are in-scope.

Example 1:

```
TodoMVC.module('Layout', function(Layout, App, Backbone, Marionette, $, _){
...
  Layout.Header = Backbone.Marionette.ItemView.extend({
  ...
```

Example 2:

```
TodoMVC.module('TodoList.Views', function(Views, App, Backbone, Marionette, $, _){
...
  Views.ItemView = Marionette.ItemView.extend({
  ...
```

Recommendation: Extend directly from the nearest module (`Marionette`, in the examples above) in all example code blocks.

**Comment by addyosmani** [comment]
@erichiggins @derickbailey, the author of Marionette wrote the chapter. I would be interested to hear what he thinks about the comments above :)

**Comment by addyosmani** [comment]
Reviewing this again, I have to agree with @erichiggins. @derickbailey if you do too, let me know and I'll be happy to adjust the examples accordingly, unless there was a good reason we maintained both variations in the examples :)

**Comment by mxriverlynn** [comment]
Oops - those should all just be Marionette.whatever, and not Backbone.Marionette.whatever :)

**Comment by addyosmani** [comment]
@erichiggins does everything look good to you now?

**Comment by erichiggins** [comment]
@addyosmani Changeset looks great, thank you!

**Comment by addyosmani** [comment]
Not at all!
