### ISSUE TITLE
Marionette ToDo Application is written backwards (logically)

### ISSUE THREAD

**Issue by erichiggins** [addyosmani/backbone-fundamentals#264]
In the section detailing the Marionette-powered ToDo Application, the details are ordered with the `Models` and `Collections` (the data) last, and the UI (`Layouts`, `Views`) first. Logically, this is backwards. Readers must first understand the data being worked on before they can understand how it is to be displayed. The defined `Views`, `Layouts`, `Routers` all referenced `Model`/`Collections` properties which were not yet mentioned. When I read this, I had to constantly scroll back and forth to understand the application example code.

**Comment by addyosmani** [comment]
@erichiggins I think the assumption here was that if you had already read the earlier chapters and exercises on your first Todo application (sans Marionette), you would have more familiarity with the data at this point and this order would be okay. Would you like to put together a pull request re-ordering these parts and we can review with Derick if he agrees this order makes the most sense?

**Comment by erichiggins** [comment]
Sorry, I thought you had included Derick on this, but it looks like you may have just been waiting for me to reply.  
I agree that missed the previous Todo application examples in the document, but I rarely read technical reference books cover-to-cover.
I might be able to do a PR, but it would likely be a few weeks until I had some time to take that task on. It might make more sense (or just be faster) for Derick to handle it, if he agrees with me conceptually.
