### ISSUE TITLE
Mismatched "spy" variable name in SinonJS: Basic Spies

### ISSUE THREAD

**Issue by erichiggins** [addyosmani/backbone-fundamentals#271]
Under "Basic Spies:"
http://addyosmani.github.com/backbone-fundamentals/#basic-spies

The test first defines the `spy`

```
var spy = this.spy();
```

But the assertion uses `spy1`

```
ok( spy1.calledOnce, 'the subscriber was called once' );
```

**Comment by addyosmani** [comment]
Thanks for reporting! We'll get this fixed soon.
