### ISSUE TITLE
Move the MVP section to the appendix/end of the book

### ISSUE THREAD

**Issue by addyosmani** [addyosmani/backbone-fundamentals#272]
As discussed with a few folks, this section is a little on the long side for beginners and would be better suited as optional reading.

**Comment by addyosmani** [comment]
@wibblymat, I noticed that you're quite a skilled writer and mentioned you have some time for open-source these days. Would you be interested in helping out with Backbone Fundamentals at all? :)

**Comment by wibblymat** [comment]
@addyosmani I'm at the disadvantage of not knowing anything about Backbone. In fact everything I know about Backbone has come from the first few sections of Backbone Fundamentals.

However, "learn either Backbone or Angular" is currently on my day job todo list so I have to get a working knowledge quickly anyway. If you are willing to give me a little time to get up to speed and I can get some fact checking/ask stupid questions I'd be willing to give it a go. I guess I should start by reading the rest of the book :)

**Comment by addyosmani** [comment]
Totally understandable, sir. More than happy to give you as long as you need to get up to speed :) I hope the book helps!

On the Backbone or Angular side, I'm actually hoping to speak to the Angular team about putting together a guide for Backbone devs, so should hopefully be useful to you if you learn one or the other.

**Comment by addyosmani** [comment]
c34fe951e060217710db2f41c33e0a72fb95f7f0 and 80c4779f4f6d2c39c052cac0c5c6a4749ccc05c0 should address the removal of the MVP section to the appendix.
