### ISSUE TITLE
Rewriting the Backbone, AMD and RequireJS section (the rest)

### ISSUE THREAD

**Issue by addyosmani** [addyosmani/backbone-fundamentals#275]

**Comment by addyosmani** [comment]
@jackfranklin Heyo! Do you think you might get a chance to finish up this piece sometime in the next week? :)

**Comment by jackfranklin** [comment]
@addyosmani I hope I should have sometime this weekend if that's okay?

**Comment by addyosmani** [comment]
That's perfect!

**Comment by addyosmani** [comment]
@jackfranklin Just checking if you've had time to look at this, sir :) I know you must be busy!

**Comment by jackfranklin** [comment]
Had a short amount of time yes, so did a bit! Will tidy up and push something tomorrow after work :)

**Comment by addyosmani** [comment]
That's awesome! You rock.

![](http://haacked.com/images/haacked_com/Windows-Live-Writer/cde4ace51f3b_117EC/feels-goodman_3.jpg)
