### ISSUE TITLE
"Resources / Extensions / Backbone Model Binding" - abandoned project

### ISSUE THREAD

**Issue by pppdns** [addyosmani/backbone-fundamentals#281]
https://github.com/derickbailey/backbone.modelbinding
"Backbone.ModelBinding Project Status: Abandoned.
I'm officially abandoning this project"

The successor of this great project is Backbone ModelBinder, which is even more powerful:
https://github.com/theironcook/Backbone.ModelBinder

**Comment by addyosmani** [comment]
@pppdns Nice! Thanks for the heads up about this. I wasn't aware the project had been abandoned.

Do you have any interest in making a PR to update the recommendation? :)
