### ISSUE TITLE
Exercise 2 needs work

### ISSUE THREAD

**Issue by wibblymat** [addyosmani/backbone-fundamentals#286]
Mostly just marking out that I am working on it. Here are the things I'm intending to cover so far.
- Style needs bringing in to line with the rest of the book
- Either add line numbers to the sample at line 229 or remove the references to them
- Might want to re-host the source code download mentioned at line 374 (currently in Dropbox)
- It covers a lot of the same ground as exercise one. Refer back to things that have already been discussed with a reminder rather than going over them fully again.
- Lots of little style things (Why is "American Psyco" (sic) credited to its real author but the others are not?)

**Comment by addyosmani** [comment]
I agree on all counts - it would be excellent to get these issues tackled. I really appreciate you taking a look at how this can be improved @wibblymat. You rock :)

Will keep this open until you're happy to address everything you set out to.

**Comment by addyosmani** [comment]
> Might want to re-host the source code download mentioned at line 374 (currently in Dropbox)

I agree. We should ideally bring this into the repo.

**Comment by addyosmani** [comment]
@wibblymat just wanted to check in to see if there were any updates on this :)

**Comment by wibblymat** [comment]
@addyosmani, sorry for the silence. I've had an unexpectedly busy time at work and a deadline for my part-time degree that crept up on me at the same time. I should be able to spend some quality writing/editing time in the later part of this week.

I do have a few small questions actually, about the license on the original tutorial and the code that goes with it. I couldn't find one anywhere so I assume you have specific permission to use it. Are there any limitations? Should I include a license with the source code we host in the repo? Can the current credit ("Credits: Björn Ekengren, Addy Osmani") at the beginning of the chapter be moved to the front matter of the book with the other credits/acknowledments in the prelude?

**Comment by addyosmani** [comment]
No worries at all, sir! I completely understand.

> Are there any limitations? Should I include a license with the source code we host in the repo? Can the current credit ("Credits: Björn Ekengren, Addy Osmani") at the beginning of the chapter be moved to the front matter of the book with the other credits/acknowledments in the prelude?

There are no limitations but thanks for asking!. The original author gave me permission and would be happy to confirm if we need to ask again. I think it would be a good idea to move the credits to the acknowledgements. We could be consistent there.

**Comment by wibblymat** [comment]
All of these things were resolved in the PR, closing.
