### ISSUE TITLE
clarify event system

### ISSUE THREAD

**Issue by ralyodio** [addyosmani/backbone-fundamentals#289]
I don't understand this sentence:

"Event is inherited by the View and Model components. That way each of them can inform other component that event of the interest to them happened."

http://addyosmani.github.com/backbone-fundamentals/#event-system

**Comment by addyosmani** [comment]
I'm not sure how "That way each of them can inform other component that event of the interest to them happened" sneaked into there, but I agree its confusing. We're going to be completely re-doing this section as a part of the incoming pull in #295 and this should be addressed there. If not, I'll re-open and update with a clarification.
