### ISSUE TITLE
Chaptering in Unit Testing

### ISSUE THREAD

**Issue by seventhsense** [addyosmani/backbone-fundamentals#290]
In 'Unit Testing' chapter, It is mentioned about 3 test frameworks, Jasmine, QUnit, SinonJS.

Now Chaptering is that ...
- Unit Testing
  - Jasmine
  - ...
  - Unit Testing Backbone Applications With QUnit And SinonJS
  - Introduction
- QUnit
- SinonJS

I think Its better that...
- Unit Testing
  - Jasmine
  - QUnit
  - SinonJS

and in QUnit chapter
- QUnit
  - Unit Testing Backbone Applications With QUnit And SinonJS
  - Introduction

Or would be more better way....

**Comment by addyosmani** [comment]
I agree we should update the TOC to be more like the above. It just makes sense. 

I'm going to commit some initial changes for it. Ideally, all sub-items under Jasmine, QUnit and Sinon need to go one level in in order for this structure to be possible. Will keep this open so it can be addressed.

**Comment by seventhsense** [comment]
Thank you for response.
And I want to say thank you again that this book is great help for me to understand Backbone.js.

About TOC, as you know, there is another way,
- Unit Testing Backbone Applications With Jasmine
- Unit Testing Backbone Applications With QUnit And SinonJS
  - QUnit
  - SinonJS

3 test framework is separate from each other, and we can combine with Jasmine and Sinon.
So I think its better.
But the latter approach might be suitable for the context...
I think both approach is not wrong, just which you prefer.

Anyway Ill keep watch this issue. 
Regards

**Comment by addyosmani** [comment]
Chaptering for testing has recently been addressed.
