### ISSUE TITLE
night mode not covered

### ISSUE THREAD

**Issue by oblitum** [addyosmani/backbone-fundamentals#303]
Hi, I just opened the prebuilt epub with chrome's [magicscroll](http://www.magicscroll.net/) extension and found out source code blocks doesn't look good at any kind of theme except the default with white background. This is not nice for night mode reading (I myself do it a lot on my Galaxy Note).

I'm not sure whether this is a thing to be taken into account or not, I'm just warning.

Regards.

**Comment by addyosmani** [comment]
I think this is something we won't (for now) take into account but I appreciate the report.
