### ISSUE TITLE
New chapters suggestion before chapter 3

### ISSUE THREAD

**Issue by hrbonz** [addyosmani/backbone-fundamentals#311]
Hi,
I think it would make sense to create a chapter before chapter 3 ("Internals", a new name for this would be nice as well, something like "Core library"). This new chapter would walk the reader through a macro view of how the different elements work together (models, collection, view, router, etc) and a very simple example of Backbone in action.

The reason for this is that I start reading your book, I get very excited about the prospect of using Backbone and I end up reading a very heavy piece (chapter 3) going in depth of every single interface the library is providing. This is walking me through a lot of lengthy explanations of a lot of elements I don't understand.

I think that adding a simple example with Backbone in action before that piece (chapter 3) would help people go through the heavy stuff. Explaining the big picture by presenting different backbone elements and how they relate would give a better frame before diving in the juicy parts (chapter 3).

**Comment by addyosmani** [comment]
Do you feel Chapter 3 is easier to digest in https://github.com/addyosmani/backbone-fundamentals/pull/307 or would you still prefer a new chapter before it?

**Comment by dcmaf** [comment]
When looking at my changes in https://github.com/dcmaf/backbone-fundamentals/tree/gh-pages/chapters for Chapter 3, be sure to take a look at the latest Chapter 2 and see if the Client Side MVC - Backbone Style section provides what you were looking for.

**Comment by hrbonz** [comment]
Will do that today.

## Stefan, from my mobile

Stefan Berder sberder@gmail.com
http://www.bonz.org/
 /(bb|[^b]{2})/

**Comment by dcmaf** [comment]
@hrbonz FYI - I just pushed a new update to my branch for chapter 3 (several sections from the end of the chapter have been moved to places later in the book, so the chapter should be thinner and more focused on the basic Backbone components).

**Comment by addyosmani** [comment]
I think this issue has been addressed given the restructure and refocus of the first few chapters of the book. If not, please ping me and we'll reinvestigate.
