### ISSUE TITLE
Update Chapter 4 Todo Tutorial for 0.9.10

### ISSUE THREAD

**Issue by dcmaf** [addyosmani/backbone-fundamentals#317]
The code and discussion in Chapter 4 will need to be updated to reflect the code changes in #301 once it has been merged.

**Comment by addyosmani** [comment]
Aha. I just pinged about this. I'll go ahead and merge 301 now.

**Comment by dcmaf** [comment]
Hmmm, it looks like the modular-todo-app practical updated in #301 goes with the Modular Development chapter and the code (which uses RequireJS) is significantly different than that in Chapter 4 even though they are both Todo app implementations. I don't think it will help with regard to updating Chapter 4 to 0.9.10.

**Comment by addyosmani** [comment]
@dcmaf how about https://github.com/addyosmani/todomvc/tree/gh-pages/architecture-examples/backbone? We upgraded this to Backbone 0.9.9 and it's basically what started the Todo app implementation used for the first practical.
