### ISSUE TITLE
Review comments: Chapter 8 - Common Problems & Solutions

### ISSUE THREAD

**Issue by dcmaf** [addyosmani/backbone-fundamentals#328]
**Section: View Nesting**
1. What is the advantage of the third variant of the view nesting (using onRender)?
2. How are the second set of approaches to view nesting more optimal than the first?
   In the first set we advocate creating new subviews each time the parent is rendered,
   but in the second set it appears to be saying this is less efficient. There are several
   approaches being shown here - what are the advantages of each? Are they all viable
   alternatives, or are some recommended over others?
3. In the last nested view example, where is this.child defined?
4. In the conclusion of the nested views section, which solution is the "first" solution?

**Section: What is the best way to manage models in nested Views?**
1. In the first sentence of the description, what does the word "this" refer to?
2. In the first part of this section there are two code samples, one showing how to nest
   models inside models and one showing how to nest views inside views (which seems like
   another variation of what was covered in the Nested Views section). The only connection
   between the two are in the funcB1 function in the nested view which appears to operate
   on an instance of modelB, though no instance of modelB is created in the example.
   
   A less abstract example might make the intention here clearer, along with additional
   discussion of what the problem is that we are addressing. It seems to be dealing with
   using nested views to manage nested models, but on first read it seems like two unrelated examples, one dealing with nested models and one dealing with nested views.
3. The Backbone-Forms example could use some more discussion - maybe explain how schema is used and show what templateB and templateC would look like.
4. I shortened the titles and added "Problem" and "Solution" headers to each section except for this one, for which the problem being addressed was unclear. This should be done for the this section as part of revising it.

**Section: Triggering updates in other Views**
1. Would it be appropriate to discuss the new feature in 0.9.10 which allows binding to events on the Backbone object, enabling it to be used like a global event bus?
2. Is there a reason to introduce a new Mediator object in this example with a publish/subscribe API rather than just using trigger/listenTo with a Backbone model (or the Backbone object itself)?

**Section: Disposing Views cleanly**
1. Would be helpful to explain that destroying views can result in memory leaks because of its bindings to events not being removed.
2. Should this section be reduced to "use listenTo()" (or removed entirely) rather than presenting an example of how to implement the functionality now provided by listenTo()?

**Section: Disposing View hierarchies**
1. This section refers to the last one, so if the last one is modified or removed, this one will need to be updated accordingly.
2. In the example, the call to unbind() should not be necessary in close() in 0.9.10.

**Section: Rendering View hierarchies**
1. Would be helpful to have a more concrete example to illustrate the scenario (don't need source code, just a scenario).
2. Reference the Marionette section of the book regarding CompositeViews.

**Section: Multiple Backbone versions**
1. This section contains four source code fragments, three of which are Backbone source code. Rather than showing how Backbone implements this support, I think it would be more helpful to have a discussion of the circumstances which would require using two versions of Backbone on the same page.
2. The implementation aspect and the way in which it supports CommonJS modules could be moved to an Internals chapter (the support for CommonJS belongs somewhere, but is it related to the ability to support multiple versions of Backbone on the same page?).

**Section: Building Model and View hierarchies**
1. Similar to the previous section, the discussion on how Backbone implements inheritance is better suited for an Internals chapter. Here, it is sufficient to show (from an application perspective) how Views can extend other Views and focus on the problem of how to call "base class" methods that are overridden in the derived class.
2. The first View inheritance example shows three levels of panels (Panel, PanelAdvanced, PanelAdvancedExtra) while the second approach has just two (Panel and PanelAdvanced). Is the second approach limited to only one level? If so, this should be mentioned. If not, it would be good to make the examples parallel.
3. Using Backbone-Super seems like a much simpler approach. Are there any disadvantages to it?

**Other Comments**

A discussion on dealing with model properties that are objects would be useful (e.g., a model with a Contact property, where a Contact has a name, address, etc.). Maybe this could be addressed in the Backbone-Forms discussion. Specifically, some discussion of how to get/set properties of such objects (i.e., set('contact.name', ... doesn't do what you might expect it to unless you use the DeepModel extension), including implicitly when fetching from a server, would be helpful.

**Comment by addyosmani** [comment]
@dcmaf I believe I've addressed many of the issues here. qq on your note in other comments: are you referring to something like http://stackoverflow.com/questions/6351271/backbone-js-get-and-set-nested-object-attribute? I assume you might be as you reference DeepModel but I could be wrong.

**Comment by dcmaf** [comment]
Yes, something along those lines. In my project, I have attributes such as addresses and location coordinates and figured this might be a fairly common problem, especially since the intuitive solution (e.g., setting location.lat or customer.state) doesn't work out of the box. I am using the DeepModel extension in my application and it works well for my purposes, but I know I saw some discussion (maybe a different StackOverflow issue) arguing that the DeepModel approach was not a good idea.

**Comment by addyosmani** [comment]
Thanks for the clarification!

**Comment by addyosmani** [comment]
@dcmaf Having reviewed DeepModel, I feel like it's something we should cover in the second edition of the book once I've had more time to use it in practice but do believe the Backbone wiki mentions it (which we do reference). 

I'm going to go through and ensure I haven't missed out anything else on this issue.

**Comment by dcmaf** [comment]
My thought wasn't so much to include a discussion of DeepModel as to just addressing the issue of how to deal with attributes that are not primitives. DeepModel works well for my purposes but it seems like the recommended solution (e.g., on StackOverflow) was to use nested models. It might be nice to have an example of that, including how that works with RESTful persistence. Maybe something to add to the #383 list on issues for the second edition.

Along those lines, Thomas Pedersen's [Backbone.Validation](https://github.com/thedersen/backbone.validation) extension might be worth mentioning as well in the validation discussion. I am using it in just its basic mode (not using the support for updating views with error messages), but it plays nice with DeepModel (e.g., I can validate that location.lat is in range [-90, 90]) and its preValidate() method provides an easy way of validating a single potential attribute change.

**Comment by addyosmani** [comment]
Thanks for the clarification! I do think this is something we should cover and perhaps in more detail than the StackOverflow thread. I've added the first paragraph from your comment above as a note to 383 and we'll definitely be exploring it (and hopefully the validation extension) in more detail in the near future
