### ISSUE TITLE
Review - Chapters 0 to 3

### ISSUE THREAD

**Issue by wibblymat** [addyosmani/backbone-fundamentals#330]
Not a lot to say about these chapters except that they look great! Here are the few notes that I do have, mostly inconsequential. Its hard to feel like you're adding value as a reviewer when there is nothing to find :)
## Introduction

> Does the following describe you?:
> 
> I want something flexible which offers a minimalist solution to separating concerns in my application. It should support a persistence layer and RESTful sync, Models, Views (with Controllers), event-driven communication, templating, and routing. It should be imperative, allowing Views to update themselves when Models change. I’d like some decisions about the architecture left up to me. Ideally, many large companies have used the solution to build non-trivial applications.

Not a technical point, but this paragraph has a lot of big words in one place. There is nothing that I could point at and say "change that", I just found my mind sliding off it.
## Fundamentals

> State is a topic which is regularly discussed when looking at Single-page applications, where the concept of state needs to be simulated.

This doesn't sound quite right. The state of the application is the state of the application - it is not simulated. The trick in JS applications is _state memory_ - recalling a previous state or sharing it with someone else.

> Javascript template libraries typically accept data in JSON

JSON is a serialisation format and is always a string. What you pass to a template is just an object. I accept that most readers will understand the meaning of the statement but it is technically wrong :)
## Backbone Basics

(Aside: This chapter is very long. I've read it three times now and it always surprises me how long it takes to get through!)

In the section **Creating new views** the first code sample doesn't work for me when I copy and paste it into the dev tools. I get a TypeError because the template doesn't exist (because I haven't added it to the DOM). This is a shame because this is one of only two examples that can't be run by just copy/pasting into the dev tools. Consider replacing:

``` javascript
todoTpl: _.template( $('#item-template').html() ),
```

with

``` javascript
todoTpl: _.template( "An example template" ),
```

or something similar. (The other non-working example mentioned does come with a tiny snippet of HTML letting you know what DOM elements it works on, so was still easy to try out)

> View logic often needs to invoke jQuery functions on the el

Not necessarily jQuery, of course. At the end of the chapter is a section on dependencies. Perhaps there it should say something like "wherever you read jQuery in this book you can mentally insert 'or Zepto'"

> To remove all callbacks for the event we pass an event name (e.g move) to the off() method on the object the event is bound to. If we wish to remove a specific callback, we can pass that callback's name as second parameter:

You don't pass the callback's name, you pass the callback itself.

> Note: To run the last example, you'll need to create a local development environment and test project, instructions for which are beyond the scope of what this book seeks to outline.

We actually do this in chapter 5, so perhaps instead of "this is beyond the scope" say "which we will cover later in the book"

> It uses jQuery or Zepto's `$.ajax()` implementations

Here we explicitly mention that it is not necessarily jQuery. For consistency I would do this everywhere or nowhere (with a note in the dependencies section as noted above)

> Implementing a new sync method can use the following pattern:

This code sample declares vars for success and error but then uses function declarations to create functions with those names. Either use function expressions or remove the vars.

**Comment by addyosmani** [comment]
Thanks for the review of these chapters, Mat :) 

I appreciate the highlight of paragraphs that we could simplify. I'll upstream some changes that adjust them accordingly.

As for the recommended changes to the Basics chapter, I'm happy to apply fixes to the points you've addressed. I don't think I disagreed with any of them. 

Was there something specific in the Basics chapter that you felt was too long or could have better fit in the appendix?

**Comment by addyosmani** [comment]
I've pushed a number of changes to address the issues reported in this. Thanks again, Mat.

**Comment by wibblymat** [comment]
That all looks good to me!

**Comment by addyosmani** [comment]
Thanks!
