### ISSUE TITLE
Review - chapter 4

### ISSUE THREAD

**Issue by wibblymat** [addyosmani/backbone-fundamentals#333]
Here are the less trivial notes on chapter 4:
1. In `js/collections/todos.js` it might be worth mentioning that `this.filter`, `this.without` and `this.last` are Underscore methods that are mixed in to Backbone.Collection so that the reader knows how to find out more about them.
2. When presenting a code sample that is an updated version of a previous sample, it would be good to have some markup that highlighted what is different. In some samples there are comments and in others there is nothing.
   In particular, the second time we see `js/views/app.js` it is difficult to tell what has changed.
3. The first four paragraphs of the **In action** section suggest that the app is currently so bare-bones that you have to add new todos through the console... which is a bit strange since we then point out that you can do this (and editing) right in the app.
4. Since the chapter is 75% done before anything is usable, perhaps the console based test could be earlier on, after the model and collection have been written.
5. In the **Completing & deleting todos** section we again have a code update. Adding `// NEW` helps, but it would still benefit from a stronger style difference.
6. Line 728:
   
   > The in-place editing and updating features are still left to be implemented [...]
   
   In-place editing and updating works fine if you follow along, so I think this paragraph can be removed.
7. The screenshot in the **Todo routing** section doesn't actually show the url fragment and in the HTML version of the book it is scaled so that it is hard to see that the word "Active" is bold in the footer.

**Comment by addyosmani** [comment]
Thanks @wibblymat!

**Comment by addyosmani** [comment]
1 and 6 should be taken care of now. I agree about 2, but we'll probably need to wait until new styles can be introduced as O'Reilly to the best of my knowledge wouldn't support this without it being in screenshot form. Maybe we could opt for comments showing the difference as a compromise?

On 3, I agree and 4 I agree that the console logging examples could be better positioned. Were you suggesting that they go before "Application View"?. If not, would you like to point out the line you would prefer to see those examples moved to or submit a PR so I can better visualize the change suggested?

I'll address 7 right now.

**Comment by addyosmani** [comment]
I took the opportunity to redo all screenshots for this section. @wibblymat could you let me know if the routing screenshot in particular is better now?

**Comment by wibblymat** [comment]
Console logging examples: just before "Application View" is where I had in mind, yes.

Routing screenshot: Much clearer
