### ISSUE TITLE
Review - chapter 6

### ISSUE THREAD

**Issue by wibblymat** [addyosmani/backbone-fundamentals#336]
The chapter is a very light introduction and few people will come out of reading the chapter ready to go off and use bbb without help. There are several unanswered questions. What does Backbone.Layout do? How does JST relate to other template systems? What is the purpose of `bbb release`? How do I actually use the new module I just generated? All of this stuff is on the web to be found but so is everything else in the chapter.

Perhaps rather than go into detail on how bbb works a better approach would be to introduce the idea and purpose of tooling - bbb, yeoman, grunt, r.js etc. - while directing the reader to learn more about them elsewhere.

There are some other problems with the current text:
1. There are instructions for downloading the Backbone Boilerplate repo from github but we never actually need it - you get it (as a sub-module of a sub-module) when you install grunt-bbb.
2. Remove the instruction `npm install -g grunt`. This is no longer appropriate as with this command you now get grunt 0.4, which should not be installed globally. bbb has a dependency on grunt 0.3.17 so once bbb is installed it will use it's own version of grunt to do things. I have removed grunt and grunt-cli from my machine and then installed bbb and all of the bbb commands work as expected.
3. I might also remove the instruction `bbb init` in the same set. If someone is just following along `bbb init` will create the project structure within the current working directory. Its annoying having to tidy up after making that mistake :) We give a fuller instruction in the very next section anyway.
4. The code samples for the project stub no longer match up with what you really get.  They are in some cases quite different which could lead to confusion. The descriptions of what each file does are still basically correct, though.
5. Line 392:
   
   > Now, you may be wondering where or how Views fit into this setup. Although Backbone Boilerplate doesn't include Views in its generated modules by default, we can easily add them ourselves as needed.
   
   Looks like bbb does now include views
6. Line 586:
   
   > I'm happy to also recommend checking out [Yeoman](http://yeoman.io) (one of my upcoming projects)
   
   It wont be "upcoming" by the time the book is out, it will be out :)
7. It might make sense to put this after the modular development chapter since you talk about AMD and requirejs config here.

**Comment by addyosmani** [comment]
@wibblymat Thanks for your feedback. I've attempted to address it in the commits above. Could you let me know what you think when you get a chance? :)

**Comment by wibblymat** [comment]
I've done a quick skim through and it looks good - all of the points I raised look sorted. I'm going to try and get through the rest of the book today and tomorrow and I'll come back and do a proper review early next week

**Comment by addyosmani** [comment]
Closing in favor of #322
