### ISSUE TITLE
Client-Side MVC - Backbone Style Section

### ISSUE THREAD

**Issue by david-mhm** [addyosmani/backbone-fundamentals#337]
Hi there!

I apologize if this isn't the right place to post this feedback or if I've missed the point of the code samples in the section: Client-Side MVC - Backbone Style.

I thought it might be helpful to fix a couple of bugs that prevent the sample code from running:
1. There are script tags for underscore, backbone, & example.js. The TodoView described two code-blocks later utilizes jquery. Add a script tag for jquery as well?
2. The second code-block names the new Todo todo1 but the todoView in code-block 3 passes in a model todo. Name these consistently?
3. TodoView isn't defined with an initialize function. As such, $el is undefined in the render function. Add something like the following to that view definition?: 
   
   ```
   initialize: function () {
       this.$el = $('#todo');
   },
   ```
4. todoView.render() is never called. I'm new to backbone & don't know if that's the best way to wrap up the example, but that seemed to work for me.

The benefit to making those 4 changes would be a working demo for anyone (like myself) who can't help but follow along with actual code. By making those revisions, I was able to create a demo.html file & paste in code-block 1, paste code-blocks 2 & 3 into example.js, & with latest copies of underscore, backbone, & jquery, the page loaded as expected.

Thanks for the great work- I've found the book extremely informative, thus far!

Cheers!
-David

**Comment by addyosmani** [comment]
Thanks for the feedback! We're currently undergoing a round of heavy technical review and I've been addressing requests for changes to those as we've been going along. Could you let me know if the issues mentioned in your ticket as still present over at backbonefundamentals.com? If so, I'll address them shortly.
