### ISSUE TITLE
Technical review from Derick Bailey

### ISSUE THREAD

**Issue by addyosmani** [addyosmani/backbone-fundamentals#341]
https://docs.google.com/file/d/10ZX1oXn4ZoFJ-f8OB3Hg6bZSB-B8g6KNzQasj_ztU6j71TY1kaHWwxXCkUxu/edit?usp=sharing

(currently private, let me know if you are a reviewer and require access)

@derickbailey Thanks for sending this in. Really appreciate the comments and feedback. I agree with many of the notes you've made and will do my best to address them.

**Comment by addyosmani** [comment]
'The “Common Problems And Solutions” Section on “How do you cleanly dispose
views and avoid memory leaks?” should either be deleted in favor of the section on
“listenTo”/”stopListening”, or re-written to use the new “listenTo” and “stopListening”
methods. The current implementation in this section is made obselete by these methods,
and is no longer needed.'

I agree with this. I feel that we should remove this particular part of the common problems
section once we've added docs for listenTo/stopListening to the basic section.

**Comment by addyosmani** [comment]
Having read through the review from Derick I feel that we've addressed most of the comments here adequately.

**Comment by mxriverlynn** [comment]
:+1:
