### ISSUE TITLE
Review - chapters 7 and 8

### ISSUE THREAD

**Issue by wibblymat** [addyosmani/backbone-fundamentals#343]
Chapter 7:
- This just feels a little like it should be at the end of the book, possibly as an appendix. Marionette and Thorax are both mentioned, too, so it makes sense putting this at least after current chapter 8.

That's it! I have some spelling/grammar tweaks coming up in a PR but nothing with the content.

Chapter 8:
- The second image in the Marionette TodoMVC section doesn't seem to add anything.
  ![image](http://addyosmani.github.com/backbone-fundamentals/img/marionette_todo1.png)
  It looks like the first image, only an element has been highlighted in the dev tools. What is it supposed to show?
- The section on Thorax starts by saying that a knowledge of Handlebars is assumed. Perhaps there ought to be a link to the Handlebars homepage or documentation?
- In the section **Custom HTML data attributes** there are some code samples that use binary operators (&&) where it would be much clearer to use if statements.

**Comment by addyosmani** [comment]
Thanks, Mat! I think the only change left to be made on this is updating the code under "Custom HTML data attributes" and pulling in your grammar PR. The Handlebars linking and so on have already been done.

For now, I'd like to avoid bloating up the appendix too much but if reviewers consistently feel it doesn't belong in the main index, I'll of course move it :)
