### ISSUE TITLE
Broken links in "Resources"

### ISSUE THREAD

**Issue by wibblymat** [addyosmani/backbone-fundamentals#346]
Three links need fixing:
1. [MVC In JavaScript With Backbone](https://github.com/Integralist/Blog-Posts/blob/master/MVC%20in%20JavaScript%20with%20Backbone.md) - 404
2. [Backbone Layout Manager](https://github.com/tbranyen/backbone.layoutmanager) - 404
3. [MarionetteJS](https://github.com/derickbailey/backbone.marionette) - Still a valid link but the repo you end up at says the content has been moved to either http://marionettejs.com/ or https://github.com/marionettejs/backbone.marionette

**Comment by addyosmani** [comment]
- https://github.com/Integralist/Blog-Posts/blob/master/2012-08-16-MVC-in-JavaScript-with-Backbone.md
- https://github.com/tbranyen/backbone.layoutmanager
- http://marionettejs.com/

**Comment by addyosmani** [comment]
Fixed in 4dc441bfcc9910e0808059f01ddc84eda0da57ae
