### ISSUE TITLE
Chapter cleanup after rearrange

### ISSUE THREAD

**Issue by jeffjo** [addyosmani/backbone-fundamentals#352]
Hey @addyosmani - It looks like some chapters were rearranged, but the old versions were never deleted from the chapters folder. When I `make html` on my machine, there are duplicate chapters being generated in the output.

**Comment by addyosmani** [comment]
Hey @jeffjo. I've attempted to fix this problem in master and believe it should be addressed now. Could you confirm if it works for you?

**Comment by jeffjo** [comment]
That did the trick, thanks!
