### ISSUE TITLE
Review comments: Chapter 8 - Modular Development

### ISSUE THREAD

**Issue by dcmaf** [addyosmani/backbone-fundamentals#354]
##### General

This chapter is very long (over 50 pages in the PDF version) and covers a wide range of subjects. It looks like some sections were originally separate chapters - I would recommend splitting them back out. For me, this is new material (I haven't used RequireJS) and I had a hard time getting through the chapter.

I would recommend grouping the AMD/RequireJS section and the modular Todo example into one chapter. It might even be possible to use the Todo example in place of the current discussion of how to use RequireJS with Backbone, though this may take more work than can be done at this point. I would suggest syncing the Todo example code with that in the earlier exercise so that the only differences are those introduced by the use of RequireJS.

The remaining sections of the chapter could either be standalone chapters or included in other chapters.

Part of what made the chapter difficult to get through was the redundancy due to the sections having been written separately. As a result, I found myself scanning paragraphs looking for what was new. I suspect this material would be much easier to digest if it were better integrated with the content of the chapters preceding it.
###### Section: Introduction

Second sentence of second paragraph: what does "It" refer to? Which specifications are being referenced?

>  Unlike some more traditional programming languages however, the current iteration of JavaScript (ECMA-262) doesn't provide developers with the means to import such modules of code in a clean, organized manner. It's one of the concerns with a specification that hasn't required great thought until more recent years when the need for more organized JavaScript applications has become apparent.
###### Section: Wrapping modules, views, and other components with AMD

In the example, is it necessary to pass 'underscore' in? It doesn't appear to be used in the model:

> ``` javascript
> define(['underscore', 'backbone'], function(_, Backbone) {
>   var myModel = Backbone.Model.extend({
> 
>    // Default attributes
>     defaults: {
>       content: 'hello world',
>     },
> 
>    // A dummy initialization method
>     initialize: function() {
>     },
> 
>    clear: function() {
>       this.destroy();
>       this.view.remove();
>     }
> 
>  });
>   return myModel;
> });
> ```
###### Section: Optimizing Backbone apps for production with the RequireJS Optimizer

Does the optimizer concatenate all the scripts into a single file? Does this lessen the benefit of using RequireJS/AMD to asynchronously load modules as needed? It looks like the next section addresses this, but it would be helpful to address here the benefits of optimizing to a single file since the introduction to AMD emphasized the benefits of loading files as-needed.
###### Section: Optimize and Build a Backbone.js JavaScript application with RequireJS using Packages
- Agree with Matt's comment on this section: needs work to integrate with the rest of the chapter/book and eliminate discussion which is redundant with content that has already been presented (make it more focused on the subject-at-hand).
- The three "Optimizing..." links to the RequireJS web site appear without any context (I thought they were references to upcoming subsections until I clicked on one of them):

> RequireJS, the (JavaScript) module loading library, has an [optimizer](http://requirejs.org/docs/optimization.html) to build a JavaScript-based application and provides various options. A build profile is the recipe for your build, much like a build.xml file is used to build a project with ANT. The benefit of building with **r.js** not only results in speedy script loading with minified code, but also provides a way to package components of your application.
> - [Optimizing one JavaScript file](http://requirejs.org/docs/optimization.html#onejs)
> - [Optimizing a whole project](http://requirejs.org/docs/optimization.html#wholeproject)
> - [Optimizing a project in layers or packages](http://requirejs.org/docs/faq-optimization.html#priority)
- I think there is a jump in complexity in this section which is overwhelming to a reader who is in the process of learning Backbone and RequireJS. Suggest moving it to later in the book or to an appendix, with a reference to that point from here.
###### Section: Build profile to optimize modular dependencies with code organized in packages

Second paragraph appears to be explaining the organization of the tree presented in the previous section, but is very dense. Needs to be broken into multiple paragraphs - possibly add annotations to the listing so the text can refer to specific parts of it.

> This strategy demonstrated builds common or site-wide groups of (core) _models_, _views_, collections which are extended from a base.js constructor which extends the appropriate backbone method, e.g. Backbone.Model. The _packages_ directory organizes code by section / responsibility, e.g. cart, checkout, etc. Notice that within the example _header_ package the directory structure is similar to the app root directory file structure. A _package_ (of modularized code) has dependencies from the common libraries in your application and also has specific code for the packages execution alone; other packages should not require another packages dependencies. A _utils_ directory has shims, helpers, and common library code to support the application. A _syncs_ directory to define persistence with your RESTful api and/or localStorage. The _vendor_ libraries folder will not be built, there is no need to do so, you may decide to use a CDN (then set these paths to : _[empty:](http://requirejs.org/docs/optimization.html#empty)_). And finally a _test_ directory for [Jasmine](http://pivotal.github.com/jasmine/) unit test specs, which may be ignored in the build as well if you choose.
###### Section: Exercise: Building a modular Backbone app with AMD & RequireJS
- First paragraph starts with "In this chapter". Is this intended to be a new chapter? It might make sense to make it one as this chapter is very long (even if the preceding section is pulled out):

> In this chapter, we'll look at our first practical Backbone & RequireJS project - how to build a modular Todo application. The application will allow us to add new todos, edit new todos and clear todo items that have been marked as completed. For a more advanced practical, see the section on mobile Backbone development.
- This section needs to be better integrated with the discussion of AMD/RequireJS earlier in the chapter as well as with the earlier Todo exercise. For example, in reading the discussion of the configuration object it is unclear to me whether this is new information or a restatement of the configuration concepts discussed earlier.
###### Section: Route-based Module Loading

Feels like this should be a separate chapter as well.
###### Section: Decoupling Backbone with the Mediator and Facade Patterns

Again, this feels like a completely new subject which belongs in its own chapter.
###### Section: Exercise
1. Under Mediator, references "aura/mediator.js". What is this a reference to?

> **Mediator**
> 
> Found in `aura/mediator.js`
###### Other
- What is best practice for organizing modules into files? With `<script>` tags, there is an incentive to minimize the number of files to keep the dependencies manageable. Is the number of files and their size not a concern when using RequireJS? For example, if you have a set of related views (such as ButtonView, ListBoxView, etc.) is it better to place them all in one file or should they each be in their own file? In Java-equivelent terms, should there be one file per package or one file per class?

**Comment by dcmaf** [comment]
@addyosmani - Regarding your comment on #353, I already opened this issue rather than adding onto #349. Adding this comment to create references between this issue and that one (i.e., effectively including this one in that one by reference).

**Comment by addyosmani** [comment]
Closing in favor of #349
