### ISSUE TITLE
Formatting Issue in Exercise 2 Book Library Sample Code

### ISSUE THREAD

**Issue by ye** [addyosmani/backbone-fundamentals#358]
It was mixing markdown syntax into the HTML markup.
![Screen Shot 2013-03-03 at 9 45 26 PM](https://f.cloud.github.com/assets/133924/215269/4b05f8c6-8478-11e2-9d9d-64da882e86a1.jpg)

**Comment by addyosmani** [comment]
This is no longer required as we've dropped this example. Thanks again for the fix, @ye!
