### ISSUE TITLE
Full set of mustache style sintax alternative

### ISSUE THREAD

**Issue by benjaminapetersen** [addyosmani/backbone-fundamentals#364]
Not sure if this would be helpful in addition to the interpolate regex example for underscore templates, but here are all three as a set if someone wanted to use them:

/**
     \* @configuration transform Underscore.js template syntax
     \* @description change the Ruby on Rails style syntax to the Mustache syntax
     \* @default <%= var %>
     \* @example: 
     \*  evaluate        {{ JavaScript code}}    execute arbitrary js code, such as loops
     \*  interpolate     {{= variable }}         prints value of variables
     \*  escape          {{- variable }}         this syntax will html escape variables
     */
    _.templateSettings = {
        evaluate:    /{{(.+?)}}/g,
interpolate: /{{=(.+?)}}/g,
        escape: /{{-(.+?)}}/g
    };

**Comment by addyosmani** [comment]
It would make for a useful addition. Thanks for sending this through!
