### ISSUE TITLE
LibraryView is not in app.js

### ISSUE THREAD

**Issue by npselheim** [addyosmani/backbone-fundamentals#365]
In Exercise 2 in Chapter 5 there is a line that reads: 

 "In LibraryView in app.js, change the line reading: ..."

However, LibraryView is not in app.js. This should instead reference the views/library.js file.

**Comment by addyosmani** [comment]
Thank you for flagging this issue. We'll address it asap!

**Comment by dcmaf** [comment]
@addyosmani I've been reviewing Chapter 5 and will be checking in some changes shortly. I'll make sure that this is addressed in those changes.

**Comment by addyosmani** [comment]
Thank you, @dcmaf! That would be fantastic. Much appreciated.
