### ISSUE TITLE
What's the best way to access the event target of view events?

### ISSUE THREAD

**Issue by bengarnett** [addyosmani/backbone-fundamentals#375]
When a view event calls a view method, the jquery event is passed to the method.

```
events: {
    'click a': 'doSomething'
},
doSomething: function(ev) {
    var target = ev.target;
}
```

The _this_ is usually bound to the element in jQuery but with backbone view event callbacks _this_ is bound to the view. It doesn't seem to be documented which leads me to believe it's not a common practice by the experts. Is this because it's not advised and there are better methods. An alternative might be to put the view event on a subview and reference the parent if needed. **What's the best practice for doing something to the target item within a list view?**

e.g. when someone click a subview item, I want to modify both the view and target subview.

```
view
    subview
    subview
    subview
```

choices:
1. put event on view, reference `this.$el` and `ev.target`
2. put event on subview, reference `this.$el` and `this.parent`
3. modify the underlying models and have event trigger the view refresh
4. other

Thanks.

Edit. it seems like ev.target is a antipattern It's complex and tight binding the children to the parent. 2/3 seem better.

**Comment by edokeh** [comment]
use `ev.currentTarget`

http://api.jquery.com/event.currentTarget/
