### ISSUE TITLE
Backbone 1.0.0 Released

### ISSUE THREAD

**Issue by dcmaf** [addyosmani/backbone-fundamentals#378]
I noticed that Backbone 1.0.0 has been released. I had started some clean-up in the Backbone Basics chapter when I noticed it. I can update that chapter to fix the things which are now incorrect (i.e., collections now have a set() and it is the default mechanism for updating after a fetch). Actually, I've already reworked the Collections and RESTFul sections, just haven't checked them in yet.

Other chapters will need to be evaluated to determine if any changes are necessitated. I think it would be desirable to have the published book be consistent with 1.0.

**Comment by addyosmani** [comment]
Wow. I was literally just about to start work on this for the Basics chapter. You sir are on fire. I would really appreciate any help you can offer with the updates to any other sections in basics/elsewhere that you feel you can assist with a 1.0 update.

I was going to go through the API changes so that we can make sure additions there as made as needed. Have you already done that/are you doing that?

**Comment by addyosmani** [comment]
We should probably also make a decision as to whether we want to move the upgrade guide/integrate it into basics. If the book ships 1.0 compatible it probably makes less sense for it to exist in the appendix.

**Comment by dcmaf** [comment]
I haven't looked at anything outside of the Basics chapter... I've got the Collection.set change covered there, along with the addition of Underscore APIs to models.

I don't know about moving the upgrade guide up - maybe break it out as a separate appendix/chapter. How many readers would be interested in what has changed from earlier versions (who won't already know)?

**Comment by addyosmani** [comment]
That's a good point. I believe that by the time the book ships many readers will already be on a more recent version of Backbone, however we could always keep it in initially and remove it in a future edition.

**Comment by addyosmani** [comment]
@wibblymat @dcmaf Still considering nixing http://addyosmani.github.com/backbone-fundamentals//#upgrading-to-backbone-0.9.10. Could you let me know (from a beginners perspective) if there's anything in there you feel we should salvage and move into the internals chapter?

**Comment by addyosmani** [comment]
If anyone could help with reviewing/answering the above it would help a lot :)

**Comment by dcmaf** [comment]
From a beginners perspective, I definitely don't see a need for moving it up and I would be okay with nixing it. I could see where it could be of use as an appendix to someone who has already been using Backbone for a while, but only if it provides greater explanation than what is provided on the Backbone.js web site.

If it is left in, it needs to be updated to cover changes up to 1.0.0. Given that, my thought would be to nix it and then focus on making sure that the book content is consistent with 1.0.0.

**Comment by addyosmani** [comment]
Thanks @dcmaf. I'm going to review where else in the basics section we're missing notes that were a part of the upgrade guide. I've accordingly nixed this section as suggeste.d

**Comment by dcmaf** [comment]
Sounds good. I just pushed some tweaks to recent changes and added a discussion to go with the new client-side MVC diagram. I'm going to review the new Mobile content and make any corrections needed there next.

Can you also take a look at the Library example and make any changes needed there? I think the call to fetch() in initialize() needs to have the {reset: true} option added.

**Comment by addyosmani** [comment]
I've pushed a number of updates to the basics section (and a minor one to the appendix) to reflect what was remaining in the upgrade guide that wasn't present in the book already. If you get a chance to have a quick look at the updates in case I missed a typo that would be greatly appreciated :)

On your question about the Library example - could you let me know what line you were referring to? As far as I could tell the only main library example is to do with emulateHTTP/JSON. I'll have another sweep through in case I missed it.
