### ISSUE TITLE
possible bug is tutorial 

### ISSUE THREAD

**Issue by dlebedynskyi** [addyosmani/backbone-fundamentals#38]
@addyosmani it seems a bug for me but  in this example

Photo = Backbone.Model.extend({
    validate: function(attribs){
        if(attribs.src == "placeholder.jpg"){
            return "Remember to set a source for your image!";
        }
    },
...
var myPhoto = new Photo();
myPhoto.set({ title: "On the beach" });

validation is passes as ok since attribs.src  is undefined - not  == "placeholder.jpg"

**Comment by addyosmani** [comment]
@Demien87 Thanks a lot for catching this. If you have a chance to review any of the other code examples, I'd appreciate any issue submissions at all. I'm hoping to replace most of these with updated ones based on the Todo example we iterate on later in the book at some point.

**Comment by dlebedynskyi** [comment]
@addyosmani  no problem. I'm just reading and working throw the book to learn backbone.js )
