### ISSUE TITLE
typo in code example

### ISSUE THREAD

**Issue by pipe-devnull** [addyosmani/backbone-fundamentals#382]
hi, 

enjoying the book so far :) spotted a typo so in a code example about views so thought i would let you know - 'extrend' should be 'extend', sorry can't give you a page number...

var TodoView = Backbone.View.extrend({
  initialize: function() {
    this.model.bind('change', _.bind(this.render, this));
  }
});

**Comment by addyosmani** [comment]
Hi there! Thanks for the heads up. I'll push the fix for this right now.
