### ISSUE TITLE
Improve the prelude

### ISSUE THREAD

**Issue by addyosmani** [addyosmani/backbone-fundamentals#390]

**Comment by stephenplusplus** [comment]
Hey Addy, I took a stab at a mini-rewrite. I just thought I'd paste it here in case anything can serve as inspiration.

Overall, I tried to make the text read slower. Efficiency in code is good, but to learn about code, I prefer the writer take their time. Of course, that's just the style in which I learn best.

I tried to let the thoughts breathe and give it more of a "I've got your back" tone. Looking back, it might be a little too far on the "cutesy" side; not sure if the tones might clash a bit. Oh well, see what you think!

...

Not long ago, "data-rich web application" was an oxymoron. A website that could gather, manage, and store data all by itself? It just wasn't possible. Today, these applications are everywhere, and you need to know how to build them.

Traditionally, web applications saved the heavy-lifting of data for servers, which would push large chunks of HTML to the browser in complete page loads. JavaScript only made an appearance to help improve the user experience-- think, "That username is not currently available. Try again!"

Now, this relationship has been inverted - client applications pull raw data from the server and render it into the browser when and where it is needed.

Before we catch up to today, let's take a quick trip back to just a few years ago. Pretend we've just been tasked with building an Ajax shopping cart that will allow users to add an item to their shopping cart without requiring a refresh. What's the first script our index.html file is going to include?

At the time, jQuery was the go-to library for this paradigm. Making Ajax requests and updating text on the page is what our friend `$` was all about. Trusting it for this back-and-forth data dance gave way to a not-so-shocking revelation: implicit model data now lives on the client side. With the server no longer being the only place that knows how many items a user has in their shopping cart, it was a hint there was a natural tension and pull of this evolution.

...

P.S. Sorry to be all up in yo' GitHub grill. I'm just a fan of your projects, and want to help them!

**Comment by addyosmani** [comment]
Thanks! I appreciate it :) I'll review your revisions soon!
