### ISSUE TITLE
Update Paginator section

### ISSUE THREAD

**Issue by addyosmani** [addyosmani/backbone-fundamentals#396]
Ensure this is up to date

**Comment by dcmaf** [comment]
@addyosmani I added a couple fixes to the Paginator section to my open pull request.

**Comment by dcmaf** [comment]
Not sure if this is a typo. In the following, should "unlikely" be "likely"?

> It makes sense to use the clientPager when your users are **unlikely** to cycle through a large number of results and you want to avoid additional network requests each time they wish to fetch the next "page" of items. As the results have all already been requested, it's just a case of switching between the ranges of data actually presented to the user.

**Comment by addyosmani** [comment]
Thanks @dcmaf. The above should be unlikely. I'll see if I can make the line easier to read as if you were uncertain I'm sure others will be too. Checking the PR now!
