### ISSUE TITLE
Confusion of terms in Introduction chapter

### ISSUE THREAD

**Issue by mpopov** [addyosmani/backbone-fundamentals#411]
In the very beginning in the “Introduction” chapter in the end of “Client-Side MVC – Backbone Style” section there is a paragraph: “While in this instance events help us relate Backbone to the MVC pattern, we will see them playing a much larger role in our SPA applications. Backbone.Event is a fundamental Backbone component which is mixed into both Backbone.Model and Backbone.View, providing them with rich event management capabilities. Note that the traditional controller role (Smalltalk-80 style) is performed by the template, not by the Backbone.View.”.  

Seems like the last sentence is wrong and right one will be: “Note that the traditional view role (Smalltalk-80 style) is performed by the template, not by the Backbone.View.”

**Comment by addyosmani** [comment]
This should be fixed in the O'Reilly version of the book. I'm going to do a double-take to ensure it's fixed on live too.
