### ISSUE TITLE
Code goes beyond the right margin

### ISSUE THREAD

**Issue by gustavolobo** [addyosmani/backbone-fundamentals#417]
In Chapter **Exercise 1: Todos - Your First Backbone.js App**, **Templates** section, in relation to the code of `#stats-template` template, the fact that you have the entire span on the same line causes that, when you open the book in Preview in Mac OS X, for example, you don't see the entire line of code.

![Page 76](http://i.imgur.com/4eAZN7m.png)

**Comment by addyosmani** [comment]
Thanks for flagging this issue. Is this the O'Reilly version of the book you're looking at? If so, we've corrected this in the final version of the book being wrapped up this week.

**Comment by gustavolobo** [comment]
Yes, it is.
Good job with the book :)
