### ISSUE TITLE
jQuery Mobile chapter feedback

### ISSUE THREAD

**Issue by addyosmani** [addyosmani/backbone-fundamentals#420]
I do have one comment on the jQuery Mobile chapter – in the opening section the last paragraph ends with “For this reason, jQMobile follows two main principles we first need to understand in order to integrate the framework to Backbone: progressive enhancement and responsive web design.”

The next section starts with “JQuery Mobile follows progressive enhancement and responsive web design principles using HTML-5 markup-driven definitions and configurations.”

Thus, we state that these are two concepts you need to understand, but then don’t explain what they are before launching into how JQuery Mobile follows them. I think it would be helpful to have a paragraph or so at the start of that section which clearly defines what the terms mean.

**Comment by addyosmani** [comment]
How about..

Progressive enhancement uses web platform features in a layered manner, allowing access to the basic content and functionality of a page, even if JavaScript is turned off or a user is not on a modern browser. An enhanced experience is offered to those with JavaScript turned on or who have a more capable recent browser.

Responsive web design (RWD) is an approach to designing pages that adapt the layout of the page to the viewing environment in order to offer a more optimal viewing experience. CSS media queries are often employed to achieve this goal.

Would those work?

**Comment by dcmaf** [comment]
Sounds reasonable to me. Maybe drop the word "recent" at the end of the first paragraph (e.g., "more capable browser").

**Comment by addyosmani** [comment]
Sounds good to me. Thanks for the review!

**Comment by addyosmani** [comment]
Added to the O'Reilly version. Will make this change to the OSS version of the book shortly.
