### ISSUE TITLE
Minor typo in Marionette section

### ISSUE THREAD

**Issue by awgreenblatt** [addyosmani/backbone-fundamentals#447]
In the Memory Management section you show how to fix the issue with ZombieView.

```
"Fixing this is easy, though..."
```

In the ensuing code, in the initialize() function we have the line:

```
this.listenTo(this.model, 'change', this.render);
```

This was changed too soon.  You want to leave the code as it was in the previous code section:

```
this.model.on('change', this.render, this);
```

because later on, when you change the view to extend Marionette.ItemView you say 

```
"Notice in this case we are using a method called ListenTo."
```

which is confusing since in that case it had already been changed to use listenTo previously.

**Comment by addyosmani** [comment]
Thank you kindly for reporting this issue, @awgreenblatt. Would you like to file a pull request against https://github.com/addyosmani/backbone-fundamentals/tree/gh-pages/chapters making this adjustment so you can get credit for the change? If not I'm happy to go ahead and make it myself :)

**Comment by awgreenblatt** [comment]
No problem, I'll take care of it.
