### ISSUE TITLE
mongoose.connect

### ISSUE THREAD

**Issue by kofiaddaquay** [addyosmani/backbone-fundamentals#451]
I am following the instructions in the book, the moment i add the following to server.js i get an error.

//Connect to database
mongoose.connect( 'mongodb://localhost', 'library_database' );
or
mongoose.connect( 'mongodb://localhost/library_database' );

The message from terminal is 
Express server listening on port 4711 in development mode
connection error: [Error: failed to connect to [mongodb://localhost:27017]]

Could it be the port? But the book mentions nothing about changing the port. It cant connect to the database. Even when i copy and paste the entire server.js from github into my js file...i get the SAME error. Can someone please help me! Been stuck for hours

**Comment by kofiaddaquay** [comment]
i found out what was going on. the mongodb server was not started. the book never mentions anything about starting the server.

**Comment by addyosmani** [comment]
Re-opening as the book should say that the server needs to be started. I'll get this added in. Sorry for it causing you to trip up!

**Comment by kofiaddaquay** [comment]
thank you! yes it would be nice to add this in. i will report anything else, as i am working thru the whole book exercises.
