### ISSUE TITLE
Please update example on page 34 

### ISSUE THREAD

**Issue by chaitanyav** [addyosmani/backbone-fundamentals#453]
Please update the example on page 34 of the book, which illustrates the validation of model attributes

From:

``` javascript
  var Todo = Backbone.Model.extend({
  validate: function(attribs){
  if(attribs.title === undefined){
  return "Remember to set a title for your todo.";
  }
  },
  initialize: function(){
  console.log('This model has been initialized.');
  this.on("invalid", function(model, error){
  console.log(error);
  });
  }
  });
  var myTodo = new Todo();
  myTodo.set('completed', false);
```

To:

``` javascript
  var Todo = Backbone.Model.extend({
  validate: function(attribs){
  if(attribs.title === undefined){
  return "Remember to set a title for your todo.";
  }
  },
  initialize: function(){
  console.log('This model has been initialized.');
  this.on("invalid", function(model, error){
  console.log(error);
  });
  }
  });
  var myTodo = new Todo();
  myTodo.set('completed', false);
  myTodo.save();
```

Documentation says "Model validation is now only enforced by default in save — not in set unless the {validate:true} option is passed. Model validation now fires an "invalid" event instead of "error"."

**Comment by addyosmani** [comment]
Could you double check if the issue is still present in the online version of the book? It's at http://backbonefundamentals.com. I just tried locating the specific example you're referring to but we've changed it since the last published version of this piece.

**Comment by chaitanyav** [comment]
I checked the online version of the book, the example uses 

<pre>
{validate: true}
</pre>

I was looking at the pdf version of the book. Closing this issue.
