### ISSUE TITLE
Backbone.Collection.update() - out of the API?

### ISSUE THREAD

**Issue by Roland1975** [addyosmani/backbone-fundamentals#455]
I am reading the online book.

http://addyosmani.github.io/backbone-fundamentals/#resettingrefreshing-collections

It seems that Backbone.Collection.update() is no longer part of the API; I mean update() is not documented on the backbonejs website. Please update the example:

theBeatles.update(['john', 'paul', 'george', 'pete']);

**Comment by addyosmani** [comment]
I need to update this to reference set instead. From the Backbone docs:

If you want to smartly update the contents of a Collection, adding new models, removing missing ones, and merging those already present, you now call set (previously named "update"), a similar operation to calling set on a Model. This is now the default when you call fetch on a collection. To get the old behavior, pass {reset: true}.

**Comment by Roland1975** [comment]
Good job. Thanks.
