### ISSUE TITLE
More Typos

### ISSUE THREAD

**Issue by teraton** [addyosmani/backbone-fundamentals#457]
Hi, first github issue, 

I'm reading through the html version of the book and there's a typo in Resetting/Refreshing Collections chapter. In the last paragraph: 

"The set() method available for Collections can also be usef ror "smart" updating of sets of models."

Usef ror should be used for.

**Comment by addyosmani** [comment]
Thanks. Confirmed. I'll get this fixed up.

**Comment by alebelcor** [comment]
Looks like this has been fixed.
