### ISSUE TITLE
Backbone target version in the book?

### ISSUE THREAD

**Issue by xjlu** [addyosmani/backbone-fundamentals#465]
I just get started to read the gh-pages branch, and it's not clear to me that which version it's targeting. For example, model validation has changed, and we have new methods: listenTo and stopListening. Since the backbone project itself is a moving target, I believe it's necessary to mention the version(s) in prelude or introduction.

**Comment by addyosmani** [comment]
The target version is 1.0. We currently mention this later on in the book but I agree it could be done earlier. I'll find a good place to integrate a note about this and update this ticket

**Comment by addyosmani** [comment]
Note added in 22e01011c05bc7f997d03fa995017c793272e0e9
