### ISSUE TITLE
First template missing "edit" and "destroy"

### ISSUE THREAD

**Issue by davidbbs** [addyosmani/backbone-fundamentals#477]
http://addyosmani.github.io/backbone-fundamentals
Under Client-Side MVC - Backbone Style
The first template is missing both the "edit" input and the "destroy" button. They are found later in the handlebars vs. underscore example. This makes the Todo application code very confusing because it is not clear where "edit" comes from.

**Comment by addyosmani** [comment]
Thanks for reporting this issue. I'll get the first template updated accordingly - it was initially meant to be kept minimal with the edit and destroy buttons being introduced later but I should have been more clear about that. Sorry for any confusion!
