### ISSUE TITLE
Apostrophe character inconsistency

### ISSUE THREAD

**Issue by kryger** [addyosmani/backbone-fundamentals#488]
I've noticed that both "plain" apostrophe (http://www.fileformat.info/info/unicode/char/0027/index.htm) and "right single quotation mark" (http://www.fileformat.info/info/unicode/char/2019/index.htm) are used interchangeably in words like _can't_, _don't_, etc. This makes it difficult to search through body for all occurences of substrings (for example looking for repeated errors)

For example, try to search for:
- **Backbone's**   [standard apostrophe]
- **Backbone’s**   [fancy single-quote apostrophe]

---

Not sure if it affects anything; is it worth switching to a single apostrophe/quoting style? BTW., this also applies to double quotes: sometimes standard "keyboard" quote characters are used (""), sometimes the left/right ones: (“”)

**Comment by addyosmani** [comment]
This was a mistake on my part and I agree that we should standardize on the apostrophe forms used. I'll add this to my todo list (and apologies for taking a while to get back to this issue!).
