### ISSUE TITLE
Backbone controller parallel

### ISSUE THREAD

**Issue by RestlessPilgrim** [addyosmani/backbone-fundamentals#495]
In the section "Client-Side MVC - Backbone Style" it says the following:

"Note that the traditional controller role (Smalltalk-80 style) is performed by the template, not by the Backbone.View"

I think this should read "is performed by Backbone.Events in Backbone.View".

**Comment by SongTanmay** [comment]
I also think its Backbone.Event instead of template.
[Pull request](https://github.com/addyosmani/backbone-fundamentals/pull/505) for the same

**Comment by SongTanmay** [comment]
In the section "Client-Side MVC - Backbone Style" it says the following:

"Note that the traditional controller role (Smalltalk-80 style) is performed by the template, not by the Backbone.View"

It should be:

"Note that the traditional _view_ role (Smalltalk-80 style) is performed by the template, not by the Backbone.View"

It should not be:
"is performed by Backbone.Events in Backbone.View"

**Comment by tudorpavel** [comment]
@addyosmani, I also think it makes more sense like this:

"Note that the traditional _view_ role (Smalltalk-80 style) is performed by the template, not by the Backbone.View"

I was reading the book on your `github.io` page and noticed this typo.
