### ISSUE TITLE
Chapter 5 can't save model to server without keywords and releaseDate

### ISSUE THREAD

**Issue by kibin** [addyosmani/backbone-fundamentals#510]
Second try. Now I red it through and have a question. Since in `defaults` of our [book model](https://github.com/addyosmani/backbone-fundamentals/blob/gh-pages/practicals/exercise-2/site/js/models/book.js) we have 

```
releaseDate: 'Unknown',
keywords: 'None'
```

we can't save the book to db, because
`Trace: { message: 'Cast to date failed for value "Unknown" at path "releaseDate"',` if we have no date or
`Trace: [TypeError: Cannot use 'in' operator to search for '_id' in none]` if we have no keywords.
With keywords we can simply wrap 'None' in object and array like this: `keywords: [{ keyword: 'None' }]` or `keywords: [{ keyword: '' }]` if we don't want to none to be our keyword.
The problem with releaseDate is a little more serious. If we simply change it to `0`, we'll get January 1970 when open the app page. I think that storing the date as `Date` in db is not the best idea, its logic and consistent, but lead to this trouble. Maybe the better idea is to store date as string so we can get this 'Unknown' string, when date is really unknown and in other cases store it as a timestamp string.
So in bookTemplate in index.html it could be like this:

```
<%= isNaN(releaseDate) ? releaseDate : $.format.date(new Date(Number(releaseDate)), 'MMMM yyyy') %>
```

And in server.js it could be something like this:

```
Book = new mongoose.Schema({
    title: String,
    author: String,
    releaseDate: String,       // Changed
    keywords: [Keywords]
});
```

**Comment by addyosmani** [comment]
Thanks for your suggestion. I've modified the tutorial to account for the adjustments you proposed.
