### ISSUE TITLE
Someting wrong with the server.js

### ISSUE THREAD

**Issue by Metoyo** [addyosmani/backbone-fundamentals#514]
//Start server
var port = 4711;
app.listen(port, function() {
    console.log('Express server listening on port %d in %s mode', port, app.setting.evn);
});

When you start $node server.js , the terminal will show a error:

ubuntu@ubuntu-dev-server:~/workspace/bookLibrary$ node server.js

/home/ubuntu/workspace/bookLibrary/server.js:34
.log('Express server listening on port %d in %s mode', port, app.setting.evn);
                                                                        ^
TypeError: Cannot read property 'evn' of undefined
    at Server.<anonymous> (/home/ubuntu/workspace/bookLibrary/server.js:34:84)
    at Server.g (events.js:175:14)
    at Server.EventEmitter.emit (events.js:92:17)
    at net.js:1052:10
    at process._tickCallback (node.js:415:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:901:3

**Comment by ghost** [comment]
Line 4: `console.log('Express server listening on port %d in %s mode', port, app.setting.evn);`

Instead of `app.setting.evn` have you tried `app.setting.env` ?

**Comment by addyosmani** [comment]
We currently reference `app.setting.env`. It's possible that this was fixed since the last time you looked at the book, however if anyone else runs into issues here please do let me know!
