### ISSUE TITLE
Are there any translation projects started?

### ISSUE THREAD

**Issue by RobinQu** [addyosmani/backbone-fundamentals#515]
Hi, 

First all, I'd like to thank you for your great writings which enlighten my journey of building a Backbone app.

And to my surprise, such useful writings are only available in English.

Are there any translation projects proposed?
Or, is it okay for anyone to start the translation project in a certain language?

**Comment by addyosmani** [comment]
We're currently coordinating all translation projects through O'Reilly at the moment.  If you're okay with that, let me know and I'll put you in touch with Mary Tressler, my editor :)

**Comment by RobinQu** [comment]
Sounds interesting. I’m OK with that.

在 2013年11月11日，上午2:46，Addy Osmani notifications@github.com 写道：

**Comment by RobinQu** [comment]
Any update?
