### ISSUE TITLE
Unclear sentence about _.bind

### ISSUE THREAD

**Issue by kanef** [addyosmani/backbone-fundamentals#535]
Under Views:

> _.bind only works on one method at a time, but supports currying and as it returns the bound function means that you can use _.bind on an anonymous function.
1.  I had to look up "currying" in Wikipedia.  Once I did,   I realized I'd already encountered the concept recently reading the recommended book _Eloquent JavaScript_, which showed examples of the technique but didn't use that term.
2.  I'm having trouble parsing the grammar of "and as it returns the bound function means".  Does it mean "and the fact that it returns the bound function means"?  Is the sentence trying to say that `_.bind` returns the argument it was passed, as a convenience?
3. An example might help clarify both of the above.

**Comment by addyosmani** [comment]
I've updated the paragraph to try being more clear and added a link to a good article that explains more on partial application and currying. I think that covering what these topics are might be out of scope for the book, but thanks for asking! I would also add that this StackOverflow answer walking through the code behind _.bind() is useful in understanding bound: http://stackoverflow.com/questions/8552908/understanding-the-code-of-bind
