### ISSUE TITLE
Larger font size

### ISSUE THREAD

**Issue by A** [addyosmani/backbone-fundamentals#537]
On my iMac 21.5 "and MacBook Pro 13" font looks very small. I propose to set the font size to 18px.

![screenshot 2014-01-27 13 25 03](https://f.cloud.github.com/assets/1410106/2006681/5476b620-8724-11e3-86f3-fd7efa9a83da.png)

![screenshot 2014-01-27 13 26 02](https://f.cloud.github.com/assets/1410106/2006682/5a1c23a8-8724-11e3-969b-6efe7aac1dd5.png)

**Comment by iamstarkov** [comment]
:up:

**Comment by adamzerner** [comment]
http://practicaltypography.com/point-size.html

**Comment by A** [comment]
> One ma­jor rea­son is cost: big­ger point sizes re­quire more paper.

@adamwiggall one major reason: web is not a paper :D

**Comment by A** [comment]
@adamwiggall hah, tl;dr. Next part of your link is nice, sorry

**Comment by adamwiggall** [comment]
Wrong adam by the looks of it.

**Comment by A** [comment]
@adamwiggall oh, sorry again! xD
