### ISSUE TITLE
Would it be ok to translate the book into other languages keeping it open-source?

### ISSUE THREAD

**Issue by jaicab** [addyosmani/backbone-fundamentals#545]
First of all, thanks for the book. It really helped me understanding Backbone.js.
So, I'm thinking about translating the book to **spanish**. Would that be ok? Do you know any other translation projects?

**Comment by addyosmani** [comment]
@jaicab I would reach out to O'Reilly as they've been handling anything to do with international translations and reviews. If you could email mary@oreilly.com she'll be happy to discuss further :)
