### ISSUE TITLE
Maybe make it clear RE the versions of Backbone and underscore to use

### ISSUE THREAD

**Issue by bailey86** [addyosmani/backbone-fundamentals#550]
Just hit issues because I was using links to an older version of Backbone.  I know under set up it says to use 

```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="http://documentcloud.github.com/underscore/underscore-min.js"></script>
<script src="http://documentcloud.github.com/backbone/backbone-min.js"></script>
```

but maybe a warning that using an older version can produce strange results.  Especially if you're like me and you'd been trying out other examples and had just left in the links to the older version of Backbone.  I sorta thought that the versions of Backbone were not that important.

**Comment by addyosmani** [comment]
Note added in 22e01011c05bc7f997d03fa995017c793272e0e9. One thing that needs to be done next is changing the setup for the book to use locked in versions of Backbone to avoid confusion. I may try switching us over to using Bower to assist with this.
