### ISSUE TITLE
version 1.1.1

### ISSUE THREAD

**Issue by anthonybrown** [addyosmani/backbone-fundamentals#551]
I just upgraded my old 1.0.0 to 1.1.1 and my apps are breaking. It's something to do with not being able to do `this.options`?
Can someone explain how to get around this ?

**Comment by addyosmani** [comment]
One of the breaking changes in 1.1.x was that you need to set `this.options = options` as part of your view initialization. I would recommend reading the Backbone upgrade guide at http://backbonejs.org/#upgrading for more information on how to handle this, but I'm going to add a note now to the book to clarify our target versions. 

See http://stackoverflow.com/questions/19325323/backbone-1-1-0-views-reading-options for an example of how to handle `this.options`.

**Comment by addyosmani** [comment]
Note added in 22e01011c05bc7f997d03fa995017c793272e0e9
