### ISSUE TITLE
Remove older book builds

### ISSUE THREAD

**Issue by addyosmani** [addyosmani/backbone-fundamentals#559]

**Comment by 1st** [comment]
What do you mean?

**Comment by addyosmani** [comment]
I should have been more clear :) At the moment we have updated builds available for some versions of the book (e.g HTML) but haven't had updated builds for others (e.g ePub). This was a reminder for myself to remove the earlier versions that had not been rebuilt in a while and ship newer ones.

**Comment by addyosmani** [comment]
Fixed thanks to your PR which just landed :)
