### ISSUE TITLE
Jasmine download area - broken link

### ISSUE THREAD

**Issue by dprotti** [addyosmani/backbone-fundamentals#568]
**Jasmine -> Getting set up** section state _“A standalone release of Jasmine can be [downloaded](https://github.com/pivotal/jasmine/downloads) from the official release page.”_ but the [downloaded](https://github.com/pivotal/jasmine/downloads) link points to a Github area with no releases available for download.
- Actual link is https://github.com/pivotal/jasmine/downloads
- Maybe it should point to https://github.com/pivotal/jasmine/releases/ given the introduction of [Github Releases](https://github.com/blog/1547-release-your-software) feature.

**Comment by addyosmani** [comment]
Thanks @dprotti. I'll get this updated!
