### ISSUE TITLE
References to `this.model.on`

### ISSUE THREAD

**Issue by ogonkov** [addyosmani/backbone-fundamentals#585]
Here is a few anti-patern in examples.

One of them in [chapter "Modularizing our models, views and collections"](http://addyosmani.github.io/backbone-fundamentals/#modularizing-our-models-views-and-collections):

``` js
this.model.on('change', this.render, this);
```

It's a bad practice to listen model's events like this, backbone have `listenTo` method for this.

``` js
this.listenTo(this.model, 'change', this.render);
```

**Comment by addyosmani** [comment]
Thanks for spotting this. Would you like to file a PR to update?

**Comment by ogonkov** [comment]
Yes, i could do that

**Comment by ogonkov** [comment]
#586
