### ISSUE TITLE
Warning on book generation - "Guide title is empty"

### ISSUE THREAD

**Issue by 1st** [addyosmani/backbone-fundamentals#598]
I tried to generate book in all formats. And the `epub` version of book generated with one warning, that we ned to fix.

```
Info(prcgen):I1052: Kindle support cover images but does not support cover HTML. Hence using the cover image specified and suppressing cover HTML in content.     URL: /tmp/mobi-w6XXvH/cover.xhtml
Warning(prcgen):W14021: Guide title is empty. Item is ignored
```

**Comment by addyosmani** [comment]
Is this currently still breaking for you?

**Comment by 1st** [comment]
I think no. As I remember - last time that I generated book - it was without errors and warnings. This issue can be closed. Thanks.
