### ISSUE TITLE
Backbone(underscore) issue with Require.js

### ISSUE THREAD

**Issue by ghost** [addyosmani/backbone-fundamentals#60]
Since I'm using node.js on the server side I prefer the "simplified CommonJS wrapping" to define modules like this:

define(function(require) {
    var $         = require('jquery'),
        _         = require('underscore'),
        Backbone  = require('backbone');

```
// require jquery plugins
require('jqueryui');
require('jquery-plugins/jquery.gritter');
require('jquery-plugins/same-height');

return Backbone.View.extend({ ... });
```

});

However, Backbone.View.extend() always raised the error "Backbone is null". 

Google lead me to this thread:

https://github.com/documentcloud/underscore/commit/0d4b1247c45083c695cab4242c084a97aa600221

and  wrapping Backbone into an AMD module like this:

define(['jquery', 'underscore'], function($, _){
  // paste Backbone.js source code here
  return Backbone;
});

fixed the issue.

I think this is worth noting it in your book.

Stephan

**Comment by addyosmani** [comment]
@bardu I was initially going to ask if the above code snippets were taking into account the recent changes to Backbone re:AMD, but I see the thread is specifically about this issue :) Thanks for bringing the thread to my attention.

I agree. This should definitely be covered.

**Comment by ghost** [comment]
For my use case it turned out that I have to do the same for underscore.js, like this:

define(function() {
  // paste underscore.js source code here
  return _;
});

**Comment by wjcrowcroft** [comment]
This is relatively easy to fix:

### YOU WILL NEED:

\- 1 x require.js
- 1 x [use.js](https://gist.github.com/1604128) by @tbranyen
- 1 x underscore.js (latest)
- 1 x Backbone.js (latest)
- 0 x hacky AMD shim versions of the latter two

### Step 1.

In your bootstrap file (the one loaded by `data-main`, and/or the one that sets up require.js config):

``` javascript

// Setup paths:
require.config({
    // Set up the use.js ('use!') requireJS plugin for non-AMD dependencies:
    use: {
        'underscore': {
            attach: function() { return this._.noConflict() }
        },
        'backbone': {
            deps: ['use!underscore', 'jquery'],
            attach: function() { return this.Backbone.noConflict(); }
        }
    },
    // other config here - paths and such:
```

### Step 2.

In your application - and any module where you use underscore/backbone:

``` javascript
define(function(require) {
    var $ = require('jquery'),
        _ = require('use!underscore'),
        Backbone = require('use!backbone');

    // rest of your stuff here.
```

This is doing it for me, anyhow. Anyone care to try it themselves and report back?

_#edit - make sure require.js knows where the `use!` plugin is. It should be in the same place as other plugins, like `text!` and `order!`. You can set this up with the `paths` object in `require.config()`._

**Comment by AgostinoSturaro** [comment]
@josscrowcroft
I can't get it to work when using classing AMD synthax.
Returning Underscore with the noConflict() makes Backbone stop working.

I'm using the latest versions of the various libs, including Use.js 0.2.0

Here's my code, the errors are:
f is null
Backbone.Model.extend is not a function
Load timeout for modules: use!backbone http://requirejs.org/docs/errors.html#timeout

``` javascript
require.config({
    paths: {
        text: 'libs/require/text',
        order: 'libs/require/order',
        use: 'libs/require/use',
        jquery: 'libs/jquery/jquery-1.7.1.min',
        underscore: 'libs/underscore/underscore-min',
        backbone: 'libs/backbone/backbone-min'
    },
    use: {
        'underscore': {
            // doesn't work
            attach: function() {
                return this._.noConflict();
            }
            // attach: "_" // works fine
        },
        'backbone': {
            deps: ['use!underscore', 'jquery'],
            attach: function(_, $) {
                return this.Backbone.noConflict();
            }
        }
    }
});

require(["use!backbone"], function(Backbone) {
    var MyModel = Backbone.Model.extend({
        defaults: {
            text: "empty"
        },
        initialize: function(){
        }
    });
});
```

**Comment by tbranyen** [comment]
@Serpenthelm For now, don't use `noConflict` on underscore.  I'm working on a way to make it possible to eliminate globals, but that code isn't done yet.

**Comment by wjcrowcroft** [comment]
Yeah, I don't use `noConflict` on underscore now. I'm haunted by visions of
users being super impressed with the application, then realising that the
JS developers left a few globals hanging around and saying "Whoa, back up a
second... screw these amateurs, let's just use a desktop app"

Hasn't happened yet though

**Comment by addyosmani** [comment]
@josscrowcroft do you think there's anything in this thread worth documenting in the book? I know there was a gotcha worth noting about noConflict() but don't know if it's something we would consider more just a reference someone can look up on the tracker if they are stuck.

**Comment by wjcrowcroft** [comment]
@addyosmani I'm not sure it's worth noting, though I suppose you could add something about using `.noConflict` to remove globals?

Hang on though, I actually use `.noConflict` in the script... and everything still works. Beats me!

I would say don't add it if it adds complexity or confusion - wait until people comment on it as being an issue then investigate.

**Comment by addyosmani** [comment]
Closing based on Joss's feedback above. Thanks everyone!
