### ISSUE TITLE
Missing dependency in require.js example?

### ISSUE THREAD

**Issue by swanson** [addyosmani/backbone-fundamentals#616]
In this code snippet:

``` javascript
define( ["lib/backbone"], function ( Backbone ) {
  var ItemView = Backbone.View.extend({
    tagName: "div",
    className: "item-wrap",
    template: _.template($("#itemTemplate").html()),

    render: function() {
      this.$el.html(this.template(this.model.attributes));
      return this;
    }
  });
  return ItemView;
});
```

The book says 

> This view doesn’t actually depend on the model it will be used with, so again the only dependency is Backbone.

Isn't Underscore also a dependency? I was expecting to see `"lib/underscore"` and `_` in the `define` parameters since it is used for templating.

What am I missing?

**Comment by addyosmani** [comment]
Earlier in the chapter we demonstrate how to setup aliases such that `lib/backbone` will define dependencies for itself on jQuery and Underscore. Is the current setup not correctly pulling in underscore?

**Comment by swanson** [comment]
Ah! That makes more sense. I wasn't considering the previous context - just this snippet as a standalone piece of code. Thanks!
