### ISSUE TITLE
"it" is ambiguous

### ISSUE THREAD

**Issue by IanDarwin** [addyosmani/backbone-fundamentals#617]
"It also doesn’t prescribe a specific template engine - while you are free to use the Micro-templating offered by Underscore.js (one of its dependencies)"

"its" is a bit unclear here - do you mean that Underscore is one of Backbone's dependencies?

Thx

**Comment by addyosmani** [comment]
I've updated the paragraph to be more clear - I meant that Underscore is Backbone's only hard dependency and so while Backbone itself doesn't prescribe a micro-templating solution, Underscore has a simple one that can be used.
