### ISSUE TITLE
Exercise 2: POST /api/books 500 error

### ISSUE THREAD

**Issue by anthonybruno** [addyosmani/backbone-fundamentals#625]
I believe there is an error in Exercise 2 regarding the jQuery POST request to `/api/books`. When I attempt to make this request in Chrome I get the following error:

```
POST http://localhost:4711/api/books 500 (Internal Server Error)
k.cors.a.crossDomain.send
n.extend.ajax 
n.(anonymous function)
```

![screen shot 2014-11-28 at 11 46 30 am](https://cloud.githubusercontent.com/assets/429837/5230930/3bb24436-76f4-11e4-9242-8d8d2fce05a6.png)

**Comment by anthonybruno** [comment]
Is this a cause of not having some additional `app.configure` parameters set? I added them to my local project found [here](https://github.com/addyosmani/backbone-fundamentals/blob/gh-pages/practicals/exercise-2/server.js) and I no longer received a 500 error.

**Comment by addyosmani** [comment]
With the `app.configure` params setup per your repo, is absolutely everything else working as expected?

If so, we can just get those straight-up added here.
