### ISSUE TITLE
Framework/Library ambiguity

### ISSUE THREAD

**Issue by MichaelArnoldOwens** [addyosmani/backbone-fundamentals#663]
Under the section "What is Backbone.js?"

> "Backbone.js is a lightweight JavaScript library that adds structure to your client-side code."

Backbone is called a library, however at the end of the section "Client-Side MVC & Single Page Apps"
Backbone is referred to as a framework:

> "Through evolution and trial and error, JavaScript developers have harnessed the power of the traditional MVC pattern, leading to the development of several MVC-inspired JavaScript frameworks, such as Backbone.js."

Is it both a library and framework? If so, the first section, "What is Backbone.js" should state this.

**Comment by tasadurian** [comment]
Many people use the terms library and framework interchangeably. I think that's what has happened here.

**Comment by addyosmani** [comment]
Agree we should be consistent. Let's say library wherever possible.

**Comment by oscarmorrison** [comment]
@addyosmani wikipedia clearly calls it a framework: https://en.wikipedia.org/wiki/Backbone.js
as does the majority of sources

**Comment by MichaelArnoldOwens** [comment]
@oscarmorrison 
http://backbonejs.org/#FAQ-why-backbone

> Backbone is a library, not a framework, and plays well with others. You can embed Backbone widgets in Dojo apps without trouble, or use Backbone models as the data backing for D3 visualizations (to pick two entirely random examples).
