### ISSUE TITLE
AppView.addOne() doesn't see the view members when fetch() is called

### ISSUE THREAD

**Issue by mariusa** [addyosmani/backbone-fundamentals#67]
More of a question than issue:

in modular-todo-app -> app.js, add this code:

addOne: function(todo) {
        console.log("addOne: " + this.statsTemplate);
         ....

While this works for items added after app is loaded, for items fetched from localStorage it will give
addOne: undefined

Any explanation why and how to fix it? (i'm trying to access any AppView member, "statsTemplate" is just an example)
Thanks

**Comment by addyosmani** [comment]
We are cleaning up the modular app and section at the moment and will address the above in that body of work. Thanks for asking about it.
