### ISSUE TITLE
No bookmarks

### ISSUE THREAD

**Issue by scribu** [addyosmani/backbone-fundamentals#7]
This looks like a very useful resource, but putting it all in a single README.md has one major drawback:

You can't link to a specific chapter of the book (and I don't think it's possible to add id attributes using Markdown).

**Comment by addyosmani** [comment]
@scribu afaik you're absolutely right (although it may be possible if we're talking about mixed HTML in there and not pure markdown) :)

My goal is to shortly put together a build process that outputs something like this: http://addyosmani.com/resources/essentialjsdesignpatterns/book/ so it's more easy to reference content and bookmark/link etc. I'm still deciding whether to stick this up on gh-pages or push to my live site.

It's definitely going to come soon, though. I'll leave this issue open as a reminder.

**Comment by addyosmani** [comment]
We're going to try addressing this issue in: https://github.com/addyosmani/backbone-fundamentals/pull/12
