### ISSUE TITLE
order of loading Underscore and Backbone - dependency issue.

### ISSUE THREAD

**Issue by dezmozz** [addyosmani/backbone-fundamentals#77]
The modular mobile app has an issue with loading underscore and backbone.

In backbone-fundamentals -> practicals -> modular-mobile-app -> app -> main.js

The Underscore module needs to be loaded before Backbone.js for the code to work 

earlier code

Line : 16  ['require', 'backbone', 'jquery', 'underscore' ],
Line : 17 function( require, Backbone, $, _ ) {

should be 

Line 16 ['require','underscore', 'backbone', 'jquery' ],
Line : 17 function( require, _, Backbone, $) {

**Comment by addyosmani** [comment]
Thanks for flagging this @dezmozz!. We'll get this fixed up shortly.
