### ISSUE TITLE
model example (2 minor thing)

### ISSUE THREAD

**Issue by Proful** [addyosmani/backbone-fundamentals#8]
I created following example using the backbone-fundamentals readme file

[Models example](https://github.com/butu5/backbone-fundamentals/blob/master/examples/models.js)

While running the code found one minor issue (most probably my mistake :) )
There is some syntax error at [L16 changeSrc](https://github.com/butu5/backbone-fundamentals/blob/master/examples/models.js#L16-22)

Also, initially got confused how to access the direct attributes. 
I thought the way to access is direct attribute is myPhoto.src [L44 direct access](https://github.com/butu5/backbone-fundamentals/blob/master/examples/models.js#L44)

**Comment by addyosmani** [comment]
Hey @butu5 :)

I've just pushed a minor change to the models example you're referring to which will hopefully clarify how changeSrc is used (see the second line of the example). I think there _may_ be a stray semi-colon missing in yours. 

I should definitely point out that although the examples in fundamentals (for the basics section) are tied together, they haven't been written in a way in which they can be dropped into a new Backbone app and just used straight-away. This may however be something I should change in the near-future.

In terms of direct access, are there any particular lines in the models section which you think could be improved to clarify how attributes should be read?

**Comment by Proful** [comment]
Thanks for reply. One more console.log I think will clear the point about the attributes. Actually in this case "attributes" is backbone specific keyword. I though you are logically referring to other attributes in this case.

var myAttributes = myPhoto.attributes;
console.log(myAttributes);
console.log(myAttributes.src);
