### ISSUE TITLE
The "MVC, MVP and Backbone.js" is super confusing

### ISSUE THREAD

**Issue by timrchavez** [addyosmani/backbone-fundamentals#84]
It reads like you're "thinking out loud" and trying to fit a square peg in to a round hole.  I was less confused before I started reading this section :)  In fact, I'd be inclined to just scrap the entire topic of MVC and MVP since it's clearly ambiguous with regards to Backbone.  Backbone is not the only framework to suffer from this identity-crisis, either.  I think there would be more value for newbies and seasoned veterans alike by just focusing simply on what types of problems Backbone is particularly suited to tackle.  It would be way more concise, and a lot more compelling, IMHO.

**Comment by addyosmani** [comment]
Could you identify some of the specific lines/parts of this section you found confusing? 

A number of developers (both those actively contributing to Backbone and those writing about it) have commented that this clarification of how Backbone fits in and around classical patterns is needed.Yes, Backbone is of course not the only framework suffering from an identity-crisis but there are two ways one can go about it. Either:

1) Completely ignore classical patterns, just assume people will understand what MVC and MVP are all about and just expect them to get where Backbone fits in. I (personally) feel this would be counter-productive. Perhaps not for a blog post, but certainly for a detailed book.
2) Actually explain it.

I'm more than happy to revise the language in the section if it doesn't read well but I have strong opinons about the need for developers to actually get what MVC is all about if they're going to use it properly.

**Comment by timrchavez** [comment]
Fair enough.  I'll reread the section and identify specific lines and sections that I found to be confusing.

**Comment by addyosmani** [comment]
Closing as we haven't had a response on this yet. If you get a chance to get back to me about the parts you found confusing I'll address. Thanks!

**Comment by timrchavez** [comment]
Thank you and sorry :/ Got busy
