### ISSUE TITLE
Pandoc epub generation

### ISSUE THREAD

**Issue by DougReynolds** [addyosmani/backbone-fundamentals#88]
Receiving error when generating pandoc with the following:
$ pandoc -f markdown -t epub --epub-metadata=metadata.xml -o backbone-fundamentals.epub README.md

pandoc: ./http://addyosmani.com/gyazo/3e5545.png: openBinaryFile: does not exist (No such file or directory)

Appears to refer to line 3734 README.md.  Am able to browse to image link.

**Comment by jgm** [comment]
See https://groups.google.com/forum/?fromgroups#!searchin/pandoc-discuss/epub/pandoc-discuss/dEAsAGVyDtw/7osKRq3NH3QJ

With current pandoc, you'll have to use relative URLs and have the image files available locally to make an epub. This may change in the future.

**Comment by DougReynolds** [comment]
So, would you suggest downloading the content and modifying the url's in README.md to a relative asset path?

**Comment by jgm** [comment]
+++ Douglas Reynolds [Mar 17 12 09:15 ]:

> So, would you suggest downloading the content and modifying the url's in README.md to a relative asset path?

Yes, that's what you need to do if you want to use current pandoc to
create an EPUB.

**Comment by DougReynolds** [comment]
My changes to the following lines after adding images to assets folder.  This allowed successful epub generation.  Thanks!

```
3726 ![screenshot 1](assets/7d4de12.png)
3730 ![screenshot 2](assets/9df4.png)
3734 ![screenshot 3](assets/3e5545.png)
```
