### ISSUE TITLE
Consistency with using `new`

### ISSUE THREAD

**Issue by JustinDrake** [addyosmani/backbone-fundamentals#9]
Sometimes you write:

Photo = new Backbone.Model.extend({

Some other times you write:

Photo = Backbone.Model.extend({

**Comment by addyosmani** [comment]
Agree this should be fixed. I'll hopefully get to update this this weekend.

**Comment by aaronmcadam** [comment]
@JustinDrake, @addyosmani Are there any issues to be aware of when using `new` or not?

**Comment by addyosmani** [comment]
@aaronmcadam both are valid but I think to avoid confusion it's best to be consistent with usage.

**Comment by tbranyen** [comment]
`Photo = Backbone.Model.extend` returns a constructor
`Photo = new Backbone.Model.extend` returns an instance of a constructor

They are two different things.

You'll encounter this error if you use `new`

``` javascript
var M = new Backbone.Model.extend({});
new M
TypeError: Object [object Object] has no method 'apply'
```

**Comment by addyosmani** [comment]
Thanks for the clarification @tbranyen. I'll make sure any inconsistencies in new being referenced where it shouldn't be are ironed out shortly :)

**Comment by addyosmani** [comment]
First stab at cleaning this up here: https://github.com/addyosmani/backbone-fundamentals/commit/202e249436092ba138fbc3da10e4417b6a3600cd

Any/all comments welcome if I've missed anything out: https://github.com/addyosmani/backbone-fundamentals

The more we discuss it on other threads, the more I think it makes sense to actually base the code snippets used throughout the basics section of the book on a fully functional application. That would make it easier to avoid some confusion of how concepts should be used.
