### ISSUE TITLE
Could not find .png files

### ISSUE THREAD

**Issue by ghost** [addyosmani/backbone-fundamentals#92]
When i ran the pandoc command it failed with "./http://addyosmani.com/gyazo/3e5545.png: openBinaryFile: does not exist (No such file or directory)".
It looked as if it was trying to find the file in the local directory rather via the web as all three png files existed at those location. So downloaded them to the root directory i was running pandoc and the xml file in and it works fine. 

However is there a way in MD that the remote file can be specified? Currently it looks like this

![screenshot 2](9df4.png)

**Comment by addyosmani** [comment]
This has been fixed in latest.

**Comment by ghost** [comment]
cool, will try it.
