### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by janbosshard** [addyosmani/backbone-fundamentals#96]
There is a minor typo in the section 'The Basics - Views - Creating new views'. 'this.el.html' is used instead of '$(this.el).html'.

**Comment by addyosmani** [comment]
Thanks for the head's up! This probably also needs to be brought in line for Backbone.latest:

> If you have been writing a fair amount of $(view.el), there's now a cached reference for that jQuery object: $el.

**Comment by addyosmani** [comment]
Fixed.
